src/Views/AppInfoView.vala
Show link buttons if URLs are present in appdata
=> Appinfo urls

README.md
As seen at `pantheon-installer`.
=> README.md: list dependencies

src/AbstractAppContainer.vala
if author is not available, fall back to project group
=> Author fallback

src/Widgets/Banner.vala
=> Style buttons to use banner theme colors

src/Widgets/Banner.vala
=> Add border and highlights to banner CSS

README.md
adds BountySource and Weblate badges
=> Add Badges to readme.md

README.md, src/Dialogs/StripeDialog.vala, src/Widgets/AbstractAppContainer.vala
Let's actually do something when you purchase an app :sweat_smile: 
The download also starts if the purchase fails and the users clicks "Pay Later"
=> Start download when purchase is compleate

src/Dialogs/StripeDialog.vala, src/Widgets/Banner.vala
=> Enable markup so we show characters correctly

src/Widgets/Banner.vala
because 12px looks weird with such large icons
=> Double column spacing in Banner

src/Application.vala
=> About fixes

src/Dialogs/StripeDialog.vala, src/Settings.vala, src/SuspendControl.vala, src/Widgets/AbstractAppContainer.vala, src/Widgets/HumbleButton.vala
=> Resolve licensing issues

README.md
=> Readme.md: explain how to force restart required messaging

src/Widgets/Banner.vala
Very subtle with colors, more pronounced with something like white:
=> add a subtle gradient to banners

src/Views/CategoryView.vala, src/Views/Homepage.vala
* Homepage is a scrolled window subclass, not box
* Remove extra boxes
* Make "Categories" label translatable
=> Homepage.vala: Remove unecessary boxes

src/Application.vala, src/Core/Houston.vala, src/MainWindow.vala, src/Views/Homepage.vala
=> Talk to Houston async and update banner in a thread

src/Widgets/CategoryFlowBox.vala
Let's refactor all the things!
=> CategoryFlowBox: Refactor category making

src/Widgets/CategoryItem.vala
Fixes #204 
Test with `LANGUAGE='fr.FR' ./appcenter`
=> Center justify Science category

src/Widgets/Banner.vala
Transition all of the CSS properties instead of just background-image
=> Banner: Transition all CSS properties

src/Core/Client.vala, src/Core/Package.vala, src/Views/AppListView.vala, src/Views/InstalledView.vala, src/Widgets/AbstractAppContainer.vala, src/Widgets/AppListRow.vala, src/Widgets/PackageRow.vala, src/Widgets/UpdateHeaderRow.vala
Fixes #12 with Ubuntu-specific backend (this actually works at the moment as oposed to the other #243 that doesn't have any data.
This is mainly a https://code.launchpad.net/~donadigo/appcenter/drivers-2/+merge/317400 copy, just adjusted to trunk and proposed here on GitHub, everything is the same as in the LP branch.
=> Implement drivers (Ubuntu specific)

src/Core/Houston.vala
For url changes in elementary/houston#438
=> Update houston newest project endpoint

po/vi.po, src/Core/Client.vala
=> Only check if we need to reboot after doing some updates

src/Core/Client.vala
=> Fix AppCenter crash with empty package cache

src/Core/Houston.vala
=> Reassign copyright from Blake to elementary

src/Core/Houston.vala, src/Views/Homepage.vala
Server side de-duplication was just merged so this should be :+1:
=> Add carousel for trending apps

src/Views/AppInfoView.vala
Move more of this widget creation stuff into construct and reduce variable scope where possible.
=> AppInfoView.vala: move more things into construct

src/Views/AppInfoView.vala
Fixes #190 
Did this as "share" instead of link specifically in case we want to eventually make this a menu with more options like mail, twitter, etc
=> AppInfoView.vala: Add share button to footer

data/icons/categories.gresource.xml, data/icons/online-account-twitter.svg, src/Views/AppInfoView.vala
=> AppInfoView: make share into a popover with email and twitter options

data/icons/categories.gresource.xml, data/icons/text-x-copying-symbolic.svg, src/Views/AppInfoView.vala
=> Add project license to footer

src/Views/AppInfoView.vala, src/Views/AppListView.vala
Places Elementary-built apps under the Curated Apps section, addressing #351
=> Update AppListView to display ElementaryOS apps as curated apps

src/Core/Package.vala, src/Views/AppListView.vala
Save some lines and kill the animals
=> Create is_native in Package.vala and use in AppListView.vala

src/Views/AppInfoView.vala
=> Don't show share popover for OS updates

src/Dialogs/StripeDialog.vala
WIP. Will fix #395 when merged.
=> Better Stripe Dialog

src/Widgets/AbstractAppContainer.vala
=> Remove 'by' from developer string

src/Views/AppListView.vala, src/Widgets/AbstractAppList.vala
* Simplify if statements
* Make method names more clear on what they do
* Check if the row is actually an `AppListRow`
=> Clean up AbstractAppList and AppListView

README.md
So developers know this is a thing.
=> Add a paragraph about loading local XML files to README

src/Views/AppListUpdateView.vala
=> Fix update view sort order

src/Widgets/AppContainers/AbstractAppContainer.vala, src/Widgets/AppContainers/AbstractPackageRowGrid.vala
AbstractAppContainer.vala: Make show_uninstall and show_open available as properties
AbstractPackageRowGrid.vala:
* Use GObject-style for existing properties
* Remove unnecessary cast
=> PackageRowGrid.vala: GObject-style

src/MainWindow.vala
=> Start searching at 3 chars instead of 2

src/Dialogs/StripeDialog.vala
As per https://en.wikipedia.org/wiki/Personal_identification_number
=> Spelling: PIN, postal code

data/io.elementary.appcenter.desktop.in.in
This addresses #486 and adds a quicklist action to show updates.
=> Add quicklist action to show updates

src/Core/Client.vala
As string.len is deprecated in favour of string.length.
=> Use string.length rather than string.len

src/Dialogs/StripeDialog.vala
Things to test:
- Make sure you can still make a purchase :)
=> Use request body to send the data

src/Core/Client.vala
Initialization of GLib.Cancellable
=> Remove a duplicated line

src/Dialogs/StripeDialog.vala
=> Mask CVC entry based on focus

src/Dialogs/StripeDialog.vala, src/Widgets/AppContainers/AbstractAppContainer.vala
* Fixes a warning about set titlebar being called on a realized window
* Fixes a warning about no transient parent
=> Fix warnings from Stripe dialog

src/CMakeLists.txt, src/Dialogs/StripeDialog.vala, src/Widgets/CardNumberEntry.vala
=> stripe dialog: new CardNumberEntry widget

src/Widgets/ReleaseRow.vala
Seems like someone just got excited? I don't see why we'd translate this
=> Don't translate bolded string

src/Views/InstalledView.vala
=> Fix Installed Back Button

data/io.elementary.appcenter.search-provider.ini.in, src/Services/SearchProvider.vala
=> SearchProvider: Use elementary code-style and make it more reliable

src/Core/Package.vala, src/Services/SearchProvider.vala, src/Widgets/AppContainers/AbstractAppContainer.vala, src/Widgets/Banner.vala, src/Widgets/Carousel/CarouselItem.vala
=> Use HiDPI icons

src/Views/AppInfoView.vala
At least alleviates the window resizing from #695
=> Ellipsize UrlButton

data/io.elementary.appcenter.appdata.xml.in
=> Fix typo in "performance" word

meson.build, src/Dialogs/StripeDialog.vala, src/Views/AppInfoView.vala, src/Views/AppListView.vala, src/Views/Homepage.vala, src/Widgets/AppContainers/AbstractPackageRowGrid.vala, src/Widgets/Banner.vala, src/Widgets/Carousel/CarouselItem.vala, src/Widgets/HumbleButton.vala, src/Widgets/ReleaseRow.vala, src/Widgets/UpdateHeaderRow.vala
=> Use granite label style constants

src/Core/Package.vala
Make sure that we show our own apps as being "Curated" in AppCenter
=> Bump curated whitelist from xenial to bionic

src/Views/AppInfoView.vala
I wanted to copy/paste some information and I couldn't, so let's fix that :)
=> AppInfoView: Make labels selectable

meson_options.txt, src/Views/AppInfoView.vala, src/meson.build
Fixes #770. I _think_ this is the right way to do this. If not, input appreciated.
=> Add sharing flag

data/application.css
=> Drop Gtk.CSS 3.18 classes

src/Core/Package.vala
=> Add is_native to is_shareable flag

meson.build
Fixes #734 
Seems we were missing the define for the conditional compilation of the badge code.
=> Add vala args for unity support

src/Dialogs/StripeDialog.vala
Little UI love in preparation for saving payment details
=> Add agent-style icon to Stripe Dialog

src/Dialogs/StripeDialog.vala
=> Change email tooltip to recomendation by @cassidyjames

src/Dialogs/StripeDialog.vala, src/Widgets/AppContainers/AbstractAppContainer.vala
=> Add null check to fix #784

src/Core/Package.vala, src/Widgets/AppContainers/AbstractAppContainer.vala
Makes the content dialog actually appear for apps that have content ratings above none, see https://github.com/elementary/appcenter/issues/808#issuecomment-422550560.
=> Check content ratings for explicit dialog

data/application.css, src/Widgets/Banner.vala
Looks like we never updated this after we did the new palette purple
=> Update default banner to new brand purple

src/Dialogs/RestartDialog.vala, src/Services/DBusServer.vala
Fixes some compilation warnings caused by the more robust DBus error throwing in newer Vala.
=> Cleanup some GLib.Error warnings

src/MainWindow.vala, src/Views/Homepage.vala
=> Remove cross-reference to MainWindow and use a signal instead

src/Core/Package.vala
`get_launchable` has the possibility of returning null.
=> Null check for launchable

src/Core/Package.vala
=> Add null checks to release sorting code

src/Core/Package.vala, src/Views/AppInfoView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala, src/Widgets/AppContainers/AbstractPackageRowGrid.vala
=> Badge plugins with the icon of their host app

po/LINGUAS
This branch adds pt and pt_BR to LINGUAS and make those two languages work in AppCenter.
=> Add Portuguese and Brazilian Portuguese to LINGUAS

data/application.css
Fixes a CSS deprecation that I'm seeing from Terminal
=> :insensitive → :disabled

src/Widgets/CategoryFlowBox.vala
=> Add math to science category

src/Widgets/CategoryFlowBox.vala
Split from #577 to make future category work more sane.
=> Alphabetize categories

data/application.css, src/Widgets/CategoryFlowBox.vala
Fixes #571 
Could probably use some love with the styling. I'd like to use an `internet-chat-symbolic`, but it doesn't exist. So the current icon is just a placeholder.
=> Add communication category

data/application.css, src/Widgets/CategoryFlowBox.vala
Split from #577.
The look I am going for on the tile is sort of that Adobe/pro-video-editor vibe. Input/improvements welcome, though. @peteruithoven mentioned the dark frame around the icon might be too low-contrast with the dark background.
=> Add Media Production category

data/application.css, src/Widgets/CategoryFlowBox.vala
=> Finance category

data/application.css, src/Widgets/CategoryFlowBox.vala
=> Super cute writing and language tile

data/application.css
=> CSS: Add bokeh to media production category

data/application.css, po/ja.po
=> Update video category CSS

src/Widgets/CategoryFlowBox.vala
So that these properties will be inherited by subclasses
=> CategoryFlowBox: Move non-construction properties to construct block

data/styles/categories.css
Just adds a little something to make it not a blank tile.
=> Add checkerboard to Graphics

data/styles/categories.css
This updates the category CSS to use theme variables instead of specific colors when it makes sense, like when we want to base something off of the foreground or background.
=> Use theme variables when it makes sense

data/io.elementary.appcenter.gschema.xml, src/Settings.vala, src/Views/InstalledView.vala
=> Remove reset paid apps gsettings key

src/Views/Homepage.vala
=> Fix compiliation when homepage banners disabled

src/Widgets/AppContainers/AbstractAppContainer.vala
As per feedback from @tintou on #977
=> AbstractAppContainer: Use source.remove

src/Core/BackendInterface.vala, src/Core/Client.vala, src/Core/Job.vala, src/Core/PackageKitBackend.vala, src/Core/UbuntuDriversBackend.vala, src/Services/DBusServer.vala, src/Views/InstalledView.vala
Cherry picking this from my flatpak branch as it offers some improvements to the speed in which the installed applications list can respond to changes from the backends.
=> Add cancellable to get_installed_applications

src/Widgets/AppContainers/AbstractAppContainer.vala
Fixes #1039 
likely caused by https://github.com/elementary/appcenter/pull/1036
=> AbstractAppContainer: Fix missing uninstall button margin

src/Views/AppInfoView.vala, src/Widgets/SizeLabel.vala, src/Widgets/UpdateHeaderRow.vala
=> AppInfoView: Fix layout for OS updates

src/Widgets/SharePopover.vala
=> Fix Twitter Share URL

src/Core/FlatpakBackend.vala, src/Core/PackageKitBackend.vala
Fixes https://github.com/elementary/appcenter/issues/1077
=> Fix get_component_from_desktop_id dbus method

data/meson.build
=> build: use define_variable for pkgconfig paths

debian/control
Not a dependency, but we think it might make the flatpak support work better :wink:
=> deb-packaging: Recommend flatpak

data/io.elementary.appcenter.appdata.xml.in
This does not contain a release tag
Also fix indentation for this file
=> Appdata: Add release info for 3.2.0

src/Widgets/AppContainers/AbstractAppContainer.vala
=> AbstractAppContainer: Also check for os_updates in install_approved

meson.build
=> Bump meson version to 3.2.1

src/Widgets/AppContainers/AbstractAppContainer.vala
=> Fix extension badge size

src/Widgets/AppContainers/AbstractAppContainer.vala
=> AbstractAppContainer: Add a badge to OS updates

src/Core/Package.vala, src/Views/AppInfoView.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala
=> Replace confusing 'version' terms with 'origin' terms

src/Views/AppInfoView.vala
Doesn't really change the number of lines, but I feel like this is more DRY and easier to read :)
And it only creates the arrow provider if the arrow buttons are actually created
=> AppInfoView: Make an ArrowButton class

.github/workflows/main.yml
Should be the first step towards retiring travis in this repo.
=> Run build and install in GitHub CI

data/io.elementary.appcenter.appdata.xml.in
Two things we missed off our appdata changelog
=> Add recent changes to appdata

data/io.elementary.appcenter.appdata.xml.in, src/Core/Package.vala
=> Mark compulsory for desktop apps as non-launchable

data/io.elementary.appcenter.appdata.xml.in, meson.build
=> Release 3.2.3

data/io.elementary.appcenter.appdata.xml.in, src/MainWindow.vala
=> Better keyboard navigation for search

src/Core/Client.vala
Cancelled isn't an error, so lets ignore those.
=> Don't throw cancelled errors to the user

data/io.elementary.appcenter.appdata.xml.in, src/Widgets/AppContainers/AbstractAppContainer.vala
=> AbstractAppContainer: switch overlay plugin icons

data/io.elementary.appcenter.appdata.xml.in, src/Views/AppInfoView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala
=> AppInfoView: fix issues with long app titles

debian/control
=> control: add polkit dep

src/MainWindow.vala
and we get a nice crossfade animation :)
=> MainWindow: Use a revealer to show/hide the updates badge

src/Widgets/AbstractAppList.vala
Just inline that namespace. View with no whitespace changes
=> AbstractAppList: inline namespace

debian/control
It is the package providing the ITS translation template for polkit files
=> Add policykit-1 to the build time dependency

src/Core/BackendAggregator.vala, src/Core/Package.vala
`index_of_nth_char` is much more complicated than what we need here since we always know that ".desktop" is 8 bytes.
=> Simplify substring calculations for component

BACKERS.md
contact@elementary.io did not respond to my emailed request on 2020-03-30 to be un-anonymized, so here we are! :)
=> Un-anonymize Matt Miller

data/io.elementary.appcenter.appdata.xml.in
=> Fix a typo: improvments --> improvements

src/MainWindow.vala
=> clicking updates badge go to installed page

data/io.elementary.appcenter.gresource.xml, data/styles/fallback.css, src/Application.vala
Fixes https://github.com/pop-os/shop/issues/215. Does not affect or override styles on elementary OS.
=> Styles: Add fallbacks for downstreams

src/Views/AppInfoView.vala
Closes https://github.com/elementary/appcenter/issues/1416
=> Fix layout for overly wide origin combobox

data/io.elementary.appcenter.gresource.xml, data/styles/application.css, data/styles/badge.css, src/MainWindow.vala, src/Widgets/CategoryItem.vala
Make sure we use shades of strawberry and not error color
Also breaks out the badge style into its own CSS file so we don't leak styles in the application
and does the same to categories while we're here
=> Fix badge color in dark style

src/Core/BackendAggregator.vala
=> BackendAggregator: Re-use component ID

src/MainWindow.vala
=> MainWindow: Use Hdy.Window and Hdy.Headerbar

src/Widgets/SharePopover.vala
fixes #1442 
If we can't get appinfo for mailto then this button won't work, so we don't pack it
=> SharePopover: Get appinfo for mailto

src/MainWindow.vala
=> Remove 'Back to Home' button on clearing the search entry

src/Views/Homepage.vala
Fixes https://github.com/elementary/appcenter/issues/1478.
e25c8c17b958cd96736194c057e53c723168a878 is responsible for the issue, according to a git bisect.
=> Fix using back button to return to category

src/Core/Package.vala
Make sure we don't get those uncurated warnings for the appcenter flatpak repo
=> Package: Update APPCENTER_PACKAGE_ORIGIN

po/LINGUAS, po/extra/LINGUAS
Adding in weblate was incomplete
=> LINGUAS: Add Panjabi and sort

data/io.elementary.appcenter.appdata.xml.in, meson.build
=> Release 3.6.1

src/Core/Package.vala
=> Package: Fix gettext syntax

src/MainWindow.vala
=> MainWindow: Show Open only when a desktop app is installed

src/Core/UbuntuDriversBackend.vala
Fixes #1548 
`ubuntu-drivers` also gives the name of a kernel modules metapackage that should be installed alongside a driver in some cases, so we need to install that too when it's there.
This makes AppCenter match the behavior of `ubuntu-drivers install` when installing nvidia drivers (and maybe other drivers that have separate modules packages)
=> UbuntuDrivers: Also install related kernel modules

data/io.elementary.appcenter.appdata.xml.in, meson.build
=> Release 3.6.2

src/Core/Package.vala, src/Views/AppInfoView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala, src/Widgets/AppContainers/AbstractPackageRowGrid.vala, src/Widgets/PackageRow.vala
Looking at this again, it seems like this makes more sense to just do in Package?
=> Package: unescape name

src/Widgets/AppContainers/AbstractAppContainer.vala
A few of these widgets are never used outside this class
=> AbstractAppContainer: Reduce variable scope

data/io.elementary.appcenter.appdata.xml.in, meson.build
Fix for the app open toasts
https://github.com/elementary/appcenter/compare/3.6.2...master
=> Release 3.6.3

src/Widgets/Banner.vala
* Remove single-use `set_default_brand ()`
* `next_package ()` and `set_background ()` are only used here so can be private
=> Banner: reduce method scope

src/Views/AppListView.vala
Fixes #1587. Uses the same language used in Onboarding.
=> AppListView: Mention Flathub in search copy

data/io.elementary.appcenter.appdata.xml.in
Try to get some translations in ahead of time
=> Appdata: add release data for 3.7.0

data/io.elementary.appcenter.appdata.xml.in, meson.build
Fixes a pretty big complaint about why Flathub apps don't show immediately in AppCenter after sideloading
=> Release 3.7.1

src/Widgets/Banner.vala
Tiny thing I noticed when working on #1645. Also bumps copyright.
=> Banner: tweak copy

src/Dialogs/StripeDialog.vala
=> StripeDialog: rewrite entry validation

src/Views/Homepage.vala
Fixes #1666. There's some styling stuff I noticed here as well but it affects master so I'll hit it in a follow-up.
=> Homepage: Fix building with homepage=false

src/Views/Homepage.vala, src/Widgets/CategoryFlowBox.vala, src/Widgets/CategoryItem.vala
=> CategoryFlowBox: fix margins

src/Views/AppInfoView.vala
Fixes #233
Pretty wordy. I also wonder if we could come up with a better title than "Not Reviewed" but more obviously meaningful than just "Non-curated" which I feel like doesn't mean anything to most people. I've seen people complain that maybe the app is reviewed by whoever maintains the remote that it's from, so it's not necessarily true to say it hasn't been reviewed. But something indicating that it's there because of Sideload I dunno. Opening for discussion :)
=> AppInfoView: Show an icon for uncurated apps

src/Views/AppInfoView.vala
=> AppInfoView: disable non-curated badge on OS updates

src/Views/AppInfoView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala
Don't store 0 price paid app
Fixes https://github.com/elementary/appcenter/issues/1704
=> Don't store 0 price paid app

data/io.elementary.appcenter.appdata.xml.in
=> AppData: Start adding 3.8.1 data

src/Widgets/AppContainers/InstalledPackageRowGrid.vala
We probably want to make changes to how releases are displayed in the future and some other things, but for now it would help to just have this class be tidier
=> InstalledPackageRowGrid: Use modern code style

data/io.elementary.appcenter.appdata.xml.in, src/Widgets/CategoryFlowBox.vala
=> CategoryFlowBox: Add Amusement to Games

src/Widgets/CategoryFlowBox.vala
Does the least to fix #1760 
I didn't see anything else here that really struck me as fitting in: https://specifications.freedesktop.org/menu-spec/latest/apas02.html
I also have PRs against [Oblivate](https://github.com/elfenware/obliviate/pull/21/files) and [Hasher](https://github.com/JeysonFlores/hasher/pull/23/files) so there would be a couple more apps here
=> CategoryFlowBox: Add Privacy & Security

src/Views/Homepage.vala
Seems kinda weird to try to set this value manually when we can reliably get the actual value on demand
=> Homepage: get currently_viewed_category accurately

data/io.elementary.appcenter.appdata.xml.in, meson.build
Just waiting a couple days on translations
=> Release 3.9.1

src/Views/AppInfoView.vala
closes #1027 
Feature can be tested with either of Internet → Starfish or Games → Sage apps.
=> Expose screenshot captions

src/Core/FlatpakBackend.vala, src/Core/PackageKitBackend.vala
Fixes a regression in #1835 that caused the homepage not to load banners etc anymore
=> Core: set AppStream.FormatStyle to COLLECTION

data/io.elementary.appcenter.appdata.xml.in, meson.build
=> Release 3.10.0

src/Widgets/AppContainers/InstalledPackageRowGrid.vala
Fixes #543 
Fixes #1137 
Fixes some release notes quirks by putting them in a dialog instead of inline in the updates view:
Also helps with window width for responsive. Both of these are at their minimum width:
Before:
After:
=> InstalledPackageRowGrid: release notes in a dialog

src/Views/AppInfoView.vala
Instead of a potentially leaky style provider for the whole screen that we have to reset every time the view loads, create a provider that only applies to that specific view and its widgets
=> AppInfoView: create accent provider per-view

src/Dialogs/StripeDialog.vala, src/Views/AppInfoView.vala, src/Widgets/AbstractAppList.vala, src/Widgets/AppContainers/AbstractPackageRowGrid.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala, src/Widgets/CategoryFlowBox.vala
Preparing for Gtk4 port. This can be rebase merged.
Didn't touch a couple classes that are already updated in #1886 to avoid conflicts
=> Use explicit properties

src/Views/CategoryView.vala
We can't subclass Gtk.FlowBox in Gtk 4, so make a box subclass instead
=> CategoryView: don't subclass Gtk.FlowBox

src/Dialogs/StripeDialog.vala
Should reduce the diff when porting to Gtk 4
* Code style
* Use boxes
* `window.set_default ()` instead of `widget.has_default`. `has_default` is read-only in Gtk 4
=> StripeDialog: code style and boxes

src/Views/AppListUpdateView.vala, src/Widgets/AbstractAppList.vala
Only used here, so remove it from the abstract class
=> Move remove_package from AbstractAppList to AppListUpdateView

src/Views/AppListUpdateView.vala, src/Views/SearchView.vala, src/Widgets/AbstractAppList.vala
Only used in AppListUpdateView
=> AbstractAppList: Remove add_package

src/Widgets/AppContainers/InstalledPackageRowGrid.vala, src/Widgets/ReleaseRow.vala
* Code style
* DRY and simplify where possible
* Use relative date time for release dates
* Use separate labels so we can use css to style
* Add an icon
=> ReleaseRow: cleanup and design update

src/Core/UpdateManager.vala, src/Views/AppListUpdateView.vala
Reduce the amount of times we iterate over lists in AppListUpdateView
=> UpdateManager: count updates size, flatpak, unpaid

data/appcenter.metainfo.xml.in
Contains a bug fix for native packages showing as uncurated
=> Release 7.1.0

src/Views/AppListUpdateView.vala
=> AppListUpdateView: Show when up to date

src/Views/AppInfoView.vala
Just makes the namespace inline, no other changes
=> AppInfoView: inline namespace

data/appcenter.metainfo.xml.in, meson.build
Translation update for the new repair dialog
=> Release 7.2.1

data/icons/categories.gresource.xml, data/icons/oars/sandbox-files-warning.svg, data/icons/oars/sandbox-files.svg, src/Views/AppInfoView.vala
Also warn about home folder access, and new icons
=> AppInfoView: warn about home permissions

src/Views/AppInfoView.vala
=> AppInfoView: use child property instead of add

src/MainWindow.vala
=> Fix deck navigation when changing package origin

src/Views/Homepage.vala
Changes from #1896 
* Explicit h/vexpand
* Use EventControllerMotion
* Use `child` instead of `add` where appropriate
* Add `pixel_size` where appropriate
=> Homepage: Gtk4 prep

src/Views/AppInfoView.vala
Minor changes from #1896
* Use `child` instead of `add` where appropriate
* add `pixel_size` where needed
=> AppInfoView: gtk4 prep

src/Views/SearchView.vala
Remove the very clever loading on scroll thing. Probably a bit slower when there's a ton of results, but that will be resolved in Gtk4
=> SearchView: bind liststore to listbox

src/Widgets/CardNumberEntry.vala
Changes from #1896 
Review with hide whitespace changes
* Remove unused timeout
* Make sure contents is actually different from string builder before changing them
* Use `set_position` instead of `move_cursor`
=> CardNumberEntry: gtk4 prep

src/Core/FlatpakBackend.vala, src/Core/PackageKitBackend.vala
For #2099
Try to fix https://github.com/elementary/appcenter/actions/runs/6872783180.
- See https://github.com/ximion/appstream/commit/3289341629b2e44714e691863316a9a5c5d8b96a
=> [appstream-1-0] More AppStream 1.0 fixes

po/POTFILES, src/MainWindow.vala, src/Views/AppInfoView.vala, src/Widgets/ActionStack.vala, src/Widgets/AppContainers/AbstractPackageRowGrid.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala, src/Widgets/AppContainers/ListPackageRowGrid.vala, src/meson.build
So that we can make AppInfoView a NavigationPage
=> Create ActionStack widget

src/MainWindow.vala
=> MainWindow: remove set_return_name function

src/Views/AppInfoView.vala
=> AppInfoView: Fix parsing locale with newer AppStream

src/Views/Homepage.vala, src/Widgets/Banner.vala
Fixes AppCenter banner not showing and doesn't require packagekit
=> Homepage: build AppCenter banner manually

README.md, meson.build, src/Core/FlatpakBackend.vala, src/Core/Package.vala, src/Views/AppInfoView.vala, src/Widgets/ReleaseRow.vala, src/meson.build
=> Bump appstream dep to 1.0.0

data/appcenter.metainfo.xml.in, src/Widgets/AppContainers/InstalledPackageRowGrid.vala
=> InstalledPackageRowGrid: only show release notes buttons if available

data/styles/MainWindow.scss, src/Views/AppListUpdateView.vala
=> AppListUpdateView: use Adw.ToolbarView

src/Views/AppListUpdateView.vala
Try to set the loading placeholder only at the most appropriate times and don't avoid showing loaded content
=> AppListUpdateView: set loading placeholder only when loading

src/Core/UpdateManager.vala
Review with hide whitespace
* Return early
* Less nesting
* Don't check the same things over and over
* Use list of updates from the updates liststore, not getting a whole new list from flatpak backend
=> UpdateManager: clean up update_cache

data/appcenter.metainfo.xml.in, meson.build
=> Release 8.0.1

src/Views/Homepage.vala
=> Homepage: remove unused return_button

data/appcenter.metainfo.xml.in, data/styles/MainWindow.scss, src/Widgets/ActionStack.vala
=> Add label for in-app purchases

src/Views/CategoryView.vala
First step towards replacing FlowBox with more efficient GridView is to use ListModels
=> CategoryView: use listmodels

src/Views/AppInfoView.vala
Fix a couple small deprecation warnings
=> AppInfo: use provider.load_from_string

src/MainWindow.vala, src/Widgets/BackButton.vala
NavigationView already sets up an action
=> MainWindow: remove back action

src/Application.vala, src/Core/Package.vala, src/Core/UpdateManager.vala, src/Dialogs/InstallFailDialog.vala, src/Dialogs/UninstallConfirmDialog.vala, src/Dialogs/UninstallFailDialog.vala, src/Dialogs/UpgradeFailDialog.vala, src/MainWindow.vala, src/Services/SearchProvider.vala, src/Views/AppInfoView.vala, src/Views/AppListUpdateView.vala, src/Views/CategoryView.vala, src/Widgets/ActionStack.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala, src/Widgets/AppContainers/ListPackageRowGrid.vala, src/Widgets/Banner.vala, src/Widgets/HumbleButton.vala, src/Widgets/SearchListItem.vala
=> Make Package name a property

data/appcenter.metainfo.xml.in, src/Widgets/ActionStack.vala, src/Widgets/HumbleButton.vala
=> ActionStack: change CTA to Install

data/appcenter.metainfo.xml.in, data/appcenter.service, data/appcenter.service.in, data/meson.build, meson.build
=> Use absolute path for Exec for DBus activation
