src/Views/AppInfoView.vala
This doubles the margin to the bottom of the app view header. This balances the look.
=> Add margin to bottom of app header

src/Dialogs/StripeDialog.vala
Fixes #162
Reason of the bug: Just take the last digit at the end. A 10 was causing it to fail since it was comparing it to a 0
=> StripeDialog: Fix CC validation false negatives

src/Core/Client.vala, src/Views/AppListView.vala, src/Widgets/AbstractAppList.vala, src/Widgets/UpdateHeaderRow.vala
Makes the restart button appear in the InfoBar instead of the header. **This again needed some refactoring how headers work and is in large portion just a port of this branch on LP + a rework how restart is checked:** https://code.launchpad.net/~donadigo/appcenter/sorting-headers/+merge/317787
Previously AppCenter updated the list every 20 milliseconds, but this is now gone with `set_header` method of `Gtk.ListBox`. This was also used to update the restart state, which is why it's now reworked.  Instead of refreshing it's state with fixed interval, we use `FileMonitor` to monitor if the `reboot-required` file is present. The `AppList` only binds the `restart_required` property to it's `InfoBar`.
You can test the restart detection with these commands:
1. Make AppCenter show the restart …
=> Make the restart button appear in the InfoBar

src/MainWindow.vala
Resolves a tiny visual issue where no space is reserved around the modebutton in which to draw the 1px box shadow
=> Add a margin for mode button to draw box shadow

src/Views/AppListView.vala, src/Widgets/AbstractAppContainer.vala, src/Widgets/AppListRow.vala, src/Widgets/PackageRow.vala
Fixes #166.
Hide the progress bar for apps that are in waiting or complete status on the update screen.
Also changes the sorting order so that the apps in the list are displayed in the order they are going to be updated in after clicking "Update All". This allows the user to follow the progress of multiple updates down the screen rather than it jumping about due to the previous alphabetical order and the apps not being updated alphabetically.
=> Only show progress bar for updating apps

src/MainWindow.vala
Fixes a regression that prevents appstream:// uri's being opened properly.
To test:
`appcenter appstream://maya-calendar.desktop`
=> Ensure the category view is open before showing anything in it

src/Views/Homepage.vala, src/Widgets/Banner.vala
Fixes #185.
Make the background transition from one color to another and move the contents from right to left.
* The entire animation duration can be controlled by changing `transition_duration` on the `stack` widget.
* The movement can be changed with `transition_type` also on the `stack` widget.
* The background is animated with CSS (`transition`) and also can be changed accordingly.
=> Animate banner

src/Views/AppListView.vala
Fixes #196
It seems like the `no_show_all` is required so explicitly show the label to fix the issue
=> explicitly show the infobar label

src/Core/Package.vala, src/Widgets/AbstractAppContainer.vala
Fixes the bug that occurs when deleting characters out of searches.
It seems to be an issue with appstream where calling `component.get_custom_value (...)` a second time, causes it to return something that was already freed from memory (probably a bug in appstream?). When the component gets deconstructed, it calls free on this object again and crashes.
By moving the `payments_key` into the `Package` class, it will only call that method once and prevent this crash.
Fixes #202.
=> Fix crash when deleting characters out of searches

src/Core/Client.vala
Adds a check if the package array returned by PackageKit is empty, resolve packages again but this time using `NOT_ARCH` filter to find the same package for other architecture. I left a comment in the code briefly explaining why the change to avoid any confusion when dealing with it in the future. This should solve installation of e.g: Steam
=> Fix resolving packages for other architectures

src/Views/AppListView.vala
Fixes #218 .
The property that decides whether to show the headers or the "Searching for updates" spinner is bound to the `updating_cache` property of `Client.vala`.
This sometimes causes the spinner to come back when we're doing updates if PackageKit decides to refresh its cache as part of the update process. To prevent this, we return false in our local copy of `updating_cache` if we know that there are some updates happening in the list. This ensures that we always show the headers while updates are happening in the list, but the spinner functions as normal outside of those cases.
Also removed an `updates_on_top` variable that wasn't used anywhere while I was in that part of the code.
=> Don't show spinner if packages are being updated

src/Views/Homepage.vala
Fixes #225 
Seems a bit counter-intuitive to show something when you're trying to hide it, but the Switcher class has built in logic to hide itself when there's only 1 item. So just trigger that after we've added the items.
=> Hide switcher when only 1 item

src/Core/Client.vala
Fixes the uncorrect update size when reopening appcenter. In some cases, multiple calls to `get_updates ()` results in duplicates being added to the changes and details set. Clearing this set prevents duplicates from being added.
Fixes #75.
=> Fix incorrect update size

src/Views/AppInfoView.vala, src/Widgets/AbstractAppContainer.vala
Don't create the screenshots box if there are no screenshots on the appdata. This will prevent the big empty "Screenshot Not Available" from appearing most of the time
=> Don't add the screenshot box if there are no screenshots

src/Views/AppInfoView.vala, src/Views/View.vala
Fixes #201 
It's either doing this, or applying manually the CSS on all the widget's manually.
=> AppInfoView: Set banner style to the banner instead of on the screen

src/Application.vala
I keep getting emails to beckersmarvin@gmail.com about issues or general questions with AppCenter although I dropped out some time ago. This isn't really annoying me (I rarely check my gmail inbox anyway), but it leads people into a dead end. Therefore I'd like to propose the removal of my email address from AppCenter's "About" dialog to reflect on the fact I'm no longer associated with the project and AppCenter development. Thanks!
=> Remove my public information from "About" dialog

src/Dialogs/StripeDialog.vala
This adds the email value to the houston callback on payment. I edited this all in GitHub so it's untested, but simple enough to probably not break the planet.
=> Add email to houston post data

src/MainWindow.vala
When searching for apps in a category, the header title was replaced with the view mode switcher when search length < 2.
See #240.
=> Fix header title being overwritten

src/Core/Client.vala
Fixes #68.
Add a handler for the updates_changed signal in PackageKit. This is fired when the package database for the system is modified in some way. Unfortunately, it's also fired when AppCenter performs any actions.
To avoid refreshing our cache all the time, we ensure that the updates_changed handler only does something when we aren't running any transactions. We assume any `updates_changed` signals coming within 2 seconds of performing actions within AppCenter are triggered by AppCenter itself and ignore them.
This already fixes the badge count being wrong after installing updates with apt, but will also help towards making sure we show the installed/update state of apps correctly even if they've been modified outside of AppCenter. This will need a little work to make sure we update …
=> Update PackageKit cache when external package changes happen

src/Core/Client.vala
Fixes #310.
For non-Ubuntu systems, this check will prevent from crashes, this also removes a hardcoded path to the exec, it's now determined by `find_program_in_path`.
=> Check if ubuntu-drivers are present

src/Views/AppInfoView.vala
Loads all the available screenshots when viewing package info. The screenshots are added to a stack and navigation is made possible with a switcher.
Screenshots marked as `DEFAULT` will be shown before other screenshots and the image with source quality is used. When one or more screenshot cannot be loaded it will place the error label in the stack instead of the image.
Closes #228.
=> Load more screenshots

src/Views/AppInfoView.vala
`folder-publicshare` is a place icon, `send-to` is the action icon
=> use correct icon name for share

src/Views/AppInfoView.vala
Fix a mistake where we've connected to the wrong signal, likely an issue caused when resolving conflicts between branches
=> AppInfoView.vala: connect to correct widget for copy link

src/Views/AppInfoView.vala
Tries to interpret common licenses into links to https://choosealicense.com and falls back to [this list](https://choosealicense.com/licenses/) if unknown
=> AppInfoView: make project license a link

src/Widgets/Banner.vala, src/Widgets/Switcher.vala
ported from #332 
> Replaced some parent.remove(child) with child.destroy(), the destroy signal is watched by parents so it's safer
=> Use destroy instead of remove

data/io.elementary.appcenter.desktop.in.in, src/Application.vala
All of the information in this dialog is now available in this app's AppInfo View in AppCenter
=> Remove about dialog

src/MainWindow.vala
I don't think this code should be there, ever. It makes the main window being restricted to a certain size. This should be a possible fix for https://github.com/elementary/appcenter/issues/367.
=> Remove maximum window size restriction

src/MainWindow.vala
Fixes https://github.com/elementary/appcenter/issues/261.
Shows a spinner in the headerbar when the backend is working on something, that is resolving Houston packages, installing / removing / updating packages, getting additional info.
=> Show a spinner when the backend is working on something

src/Widgets/AbstractAppContainer.vala
This crash was caused by having the Homepage fetching the packages from Houston and updating their states in a Thread, hence why this signal and updating UI was also ran in a Thread . This should fix the thread crashes.
=> Fix threads crash

src/Widgets/HumbleButton.vala
The amount shouldn't be set using `Object ()` since it's not a construct property, it now has only a default value of 1.
This should fix 
`#11 0x00007ffff6e869e7 in gtk_style_context_get_style_valist () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0` crashes when closing the AppCenter.
=> Fix get_style_valist crashes

src/Views/AppListView.vala
Fixes sorting in `AppListView`. The `if` condition was wrong and assumed that if some package is native then sort them by nativity. This is now changed to compare if the rows are actually different.
There is also a wrong parameter passed to the last `return` line:
return **row1**.get_name_label ().collate (**row1**.get_name_label ());
It compares two same labels which will always return that they are equal. This should be changed to `row2`, but since the same is done in the default `AbstractAppList` class, we will just call the `base`.
Here you go with screenshots what has actually changed:
**Before:**
**After:**
=> Fix sorting in AppListView

src/Views/AppInfoView.vala, src/Widgets/ReleaseRow.vala
* All section headers use h2
* xalign instead of halign (it's a bit safer with wraps)
* Remove extra indentation
Before:
After:
=> AppInfoView.vala: What's new styling

README.md
Adds a couple of lines to the README so people know about / how to use the `-f` flag.
=> Document fake-package-update flag

src/Core/Package.vala, src/Views/AppInfoView.vala, src/Views/AppListUpdateView.vala, src/Views/AppListView.vala, src/Widgets/AbstractAppContainer.vala, src/Widgets/AbstractAppList.vala, src/Widgets/PackageRow.vala, src/Widgets/ReleaseListBox.vala, src/Widgets/ReleaseRow.vala
Fixes #24.
This is work in progress, but I would still like to get feedback how can I fix some problems with the UI because I just can't get over them:
* The "Update" button stays always in the middle of the package row, even if you expand the version description
* When expanding the version description, the expander changes it's place and so the expander arrow changes it's place so that you can't click it again without moving the mouse.
Some changes in the code to make the PackageRow display the release information is moving some methods from `ReleaseListBox` and `ReleaseRow` to the core `Package` class so they can be used outside of these specific widgets.
=> Show newest changelog in the updates view

src/Widgets/HumbleButton.vala
Fixes #447.
Does what it says. Creates a popover only when the arrow is actually clicked.
=> Don't create popovers everytime in HumbleButton

src/Core/Package.vala, src/Views/AppInfoView.vala
Fixes #383.
Adds `is_shareable` and makes drivers not shareable for now. The `return component.id == OS_UPDATES_ID;` is intentional since that string is already declared in `OS_UPDATES_ID` constant.
=> Add is_shareable property

src/Views/AppInfoView.vala
Fixes #441.
There are no side margins in `AppInfoView` class which leads pages like Vocal page to not have any margin on the sides due to long labels. This fixes it.
=> Add side margins to AppInfoView

CMakeLists.txt, data/CMakeLists.txt, data/io.elementary.appcenter-daemon.desktop.in
Fixes #471.
Adds the daemon desktop file back. This was my fault and I apologize for that, **the change will require removing the daemon patch in the packaging on LP.**
=> Add daemon desktop file back

data/application.css, src/Widgets/Banner.vala
Fixes a regression in #519 regarding transition duration
Make sure we don't inherit icon-shadow or text-shadow from somewhere else (fixes an issue in gtk 3.22)
=> Banner CSS Fixes

data/application.css, src/Application.vala
Also solves a warning by setting `transient_for` and changes "Close" to "Ignore" while we're here
=> Style cache update fail dialog details as Terminal

src/Application.vala
Removes app_icon that was previously used for the about dialog and is now deprecated in Granite.
=> Remove app_icon

src/Widgets/AppContainers/AbstractPackageRowGrid.vala
Fixes #535 
I can't test this right now because I don't have any updates with a changelog but it appears that currently both the action_stack and the releases stack are being attached to the grid at `2, 0`. This should theoretically resolve the issue.
Please test thoroughly on a system that is experiencing the problem. Also check that this doesn't break other views since this is an abstract widget that is presumably used in other places.
=> Pack action_stack after release stack

src/MainWindow.vala
This PR implements support for back buttons on the mouse. Thus, when you press the back button on the mouse (on mice that have this), it will go to the previous view. It also adds an accelerator for GDK_KEY_Back to the same button, for support of keyboard-based back buttons.
Fixes #23 
Fixes pop-os/shop#19
=> Mouse back button

schemas/io.elementary.appcenter.gschema.xml, src/Settings.vala, src/Views/InstalledView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala
This is the first step on the road to #502 
I decided to track applications that had been paid for rather than ones that hadn't for a number of reasons:
* Tracking not paid is more complicated since you can "not pay" for an application a number of times by updating it. So that would need more tracking to make sure it didn't get re-added to the not paid list. Once it's been paid for once, we can consider it no longer naggable, which is easier.
* It will be marginally harder for people to manually fiddle with GSettings and make it stop asking since they'll have to put a desktop ID in rather than take one out.
* Adding stuff to arrays is easier than taking stuff out? Maybe that's an excuse... :woman_shrugging: 
Also, I've stuck some code in there that initially populates the list with all …
=> Track paid-for applications in GSettings

src/Widgets/AppContainers/AbstractAppContainer.vala
Fixes #306 
Makes the HumbleButton show "Free" and pre-selects $0 if an application already appears in the paid-for applications list as implemented in #559.
=> Set amount to 0 on HumbleButton for already paid-for applications

src/Dialogs/StripeDialog.vala
We accidentally broke this fixing terminal warnings
=> Fix regression showing privacy link

src/Application.vala, src/Core/Client.vala, src/MainWindow.vala
This hooks up @danrabbit 's update badge to the logic behind the client, which allows it to be shown and hidden based on whether updates are available or not. It also updates the label text with the correct number of updates available.
This is the fixed PR.
=> Add logic to update badge

src/Core/Client.vala
This fixes compilation against a PackageKit that was built with the latest vala (0.40 branch).
WARNING: This breaks compilation with older versions of vala (and PackageKit that hasn't been rebuilt with the new vala), so you will only want to merge this after those updated packages are available for you.
=> Core/Client.vala: adapt to vala 0.40 / PackageKit changes (Fixes #619)

src/Services/DBusInterfaces.vala, src/SuspendControl.vala
Fixes a warning that `DBus methods are recommended to throw at least `GLib.Error'`
=> Replace IOError with GLib.Error

src/Application.vala, src/Core/Client.vala, src/MainWindow.vala, src/Views/SearchView.vala, src/Widgets/SharePopover.vala
Needed for https://github.com/elementary/files/issues/446.
When searching also searches for mimetypes so that e.g Files can invoke AppCenter to search by mimetype.
I've made up a little "type" URI scheme to distinguish the type and appstream URI's, example:
`io.elementary.appcenter type://application/pdf`
=> Search by mimetype

src/Utils.vala, src/Views/Homepage.vala, src/meson.build
Inspired by changes in Pop!_Shop. Fixes #750. Explicitly doesn't shuffle the homepage banner, as I like the newest apps getting their big debut moment.
=> Shuffle trending and recently updated

src/Widgets/CategoryFlowBox.vala
Split from #577. Added since [FreeDestkop.org Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html) don't require a relevant primary category. This gives us a bigger pool of software to browse without reverting to search.
=> Add additional categories to Video

src/Widgets/CategoryFlowBox.vala
Split from #577. According to FD.o:
>Monitor application/applet that monitors some resource or activity
Added since [FreeDestkop.org Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html) don't require a relevant primary category. This gives us a bigger pool of software to browse without reverting to search.
=> Add Monitor to System category

src/Widgets/CategoryFlowBox.vala
Split from #577. Added since [FreeDestkop.org Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html) don't require a relevant primary category. This gives us a bigger pool of software to browse without reverting to search.
=> Add P2P to Internet category

src/Widgets/CategoryFlowBox.vala
Split from #577. Added since [FreeDestkop.org Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html) don't require a relevant primary category. This gives us a bigger pool of software to browse without reverting to search.
=> Add additional categories to Office

src/Widgets/CategoryFlowBox.vala
Split from #577.
This is added since [FreeDestkop.org Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html) don't require a relevant primary category. This gives us a bigger pool of software to browse without reverting to search.
=> Add Music to Audio category

src/Widgets/CategoryFlowBox.vala
Split from #577. Added since [FreeDestkop.org Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html) don't require a relevant primary category. This gives us a bigger pool of software to browse without reverting to search.
=> Add additional categories to Development

src/Widgets/CategoryFlowBox.vala
This is something I was working on for Pop!_Shop, but could also benefit us in AppCenter. Split from #577.
- Update copyright while we're here
- Add the following categories to this category:
- ArtificialIntelligence
- Astronomy
- Biology
- Calculator
- Chemistry
- ComputerScience
- DataVisualization
- Electricity
- Electronics
- Engineering
- Geology
- Geoscience
- Math
- NumericalAnalysis
- Physics
- Robotics
- ~~Add "Math" to the category title to make it more precise~~ _Omitted due to string freeze #753_
These are added since [FreeDestkop.org Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html) don't require a relevant primary category. This gives us a bigger pool of software to browse without reverting to search.
This also helps us get away from …
=> Add several "additional categories" to Science

data/application.css
Simpler, smaller implementation of #692. Just sets a hover shadow on the big banner without affecting margins.
=> Shadow on home banner

src/Core/Package.vala
Remove releases with `null` version so that `vercmp` doesn't crash AppCenter.
=> Fix HostsManager page crash

src/Views/Homepage.vala
Fixes #795. Right now it just stops appending `.desktop` when looking for IDs, which fixes it for new apps but doesn't display any apps with the legacy format (like Clairvoyant and Taxi).
=> Fix homepage banner

src/Dialogs/StripeDialog.vala
While this is hidden in our stylesheet, it can show up in other stylesheets. The null default is the app ID, which is ugly, and an empty string can look really strange. I figure setting something sane like "Payment" is fine for when it does show up but isn't critical info for us at all since we're hiding it.
=> Add title to StripeDialog

src/Application.vala, src/Core/ComponentValidator.vala
The CONFIGDIR meson path definition doesn't contain the slash at the beggining hence it currently fails to read the blacklist file. This fixes it.
=> Fix blacklist path

src/Core/Client.vala, src/Core/Package.vala, src/Views/AppInfoView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala
Fixes #683 
And clean up a little bit of formatting while we're here.
In some cases we still want the `Component.id` field (i.e. the bit that's in the `<id></id>` tags in the appstream file. We use that for matching appstream components uniquely and sending to Houston, but for code that's involved in the launching of appstream applications, we should check if there are any `<launchable>` entries first and use those to construct the desktop app info.
I've left in a fallback to trying to launch based on the `id` field as I don't think all apps will have the `launchable` for the forseeable future.
=> Replace deprecated Component.get_desktop_id

src/Widgets/AppContainers/AbstractAppContainer.vala
Fixes #838 
May also fix #837 
This is an alternative to removing the size group (see #856 ).
The visibilities of buttons and progress widget are controlled entirely by GtkStack.visible_child in AbstractAppContainer instead of setting the 'visible' property.  The code is rather cumbersome as you have to add a dummy widget which does not get drawn (an EventBox was used) as an alternative to showing the button since it is not allowed to set the visible child to 'null'.  You cannot add all the buttons to one stack because more than one may be shown at the same time.
=> Do not alter buttons visibility property - use stacks to hide.

data/styles/categories.css, src/Widgets/CategoryFlowBox.vala
Open to feedback/thoughts. Trying to get rid of more magic numbers and use the palette, but the non-symbolic icon looked weird on a background of the exact same colors. And I tried inset on a lighter shade to avoid yet-another-white-on-dark tile.
=> Use palette and symbolic for system

src/Views/AppInfoView.vala
Somewhere along the line, some gaps were introduced that make the header look kind of funny. This corrects that and also shrinks the size of the app author label a bit:
=> AppInfoView: Fix alignment of labels in header

src/Application.vala, src/Core/Client.vala, src/Core/UbuntuDriversBackend.vala, src/Views/Homepage.vala, src/Views/InstalledView.vala, src/meson.build
Start to form the concept of separate backends and move the `ubuntu-drivers` logic into one.
The concept of backends is not complete yet as drivers are still technically part of the "PackageKit" backend. So we abuse the fact that AppCenter only has a PackageKit backend so far to prevent building a load more shims in the new drivers backend.
This will need to be done, but I'll do it as a separate PR to keep things easier to review.
Things to test:
* All things related to drivers
* The installed/update view's list of packages
=> Move drivers logic to separate class

src/Application.vala, src/Core/ChangeInformation.vala, src/Core/Client.vala, src/Views/Homepage.vala, src/Views/InstalledView.vala
During testing downstream, @isantop and @mmstick found and were able to reproduce some crashing issues when cancelling package operations:
https://github.com/pop-os/shop/pull/117#pullrequestreview-219171652
Since moving more of the backend logic into threads, some of the signals being fired back to the UI were now running in non-UI threads causing issues. If we wrap the firing of these signals in an `Idle.add` we can ensure they run on the main GTK thread.
=> Fix crashing issues when cancelling package operations

src/Core/ChangeInformation.vala, src/Core/Package.vala, src/MainWindow.vala, src/Views/AppListUpdateView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala
Further testing by @mmstick found more crashing issues relating to crashing package operations. I wasn't able to reproduce all of these, but I have cleaned up more instances where UI operations could be called from other threads and this is apparently more stable.
=> More package operation cancellation crash fixes

src/Application.vala
Because of the complex mess of conditionals in Homepage.vala, it's very difficult to fire the signal that instructs the package cache to be refreshed, which triggers an update check. So currently, when `-Dhomepage=false` is set during compilation, you end up with an AppCenter that doesn't check for package updates. This fixes that.
=> Check for updates when -Dhomepage=false

src/Widgets/AppContainers/AbstractAppContainer.vala
Cherry picked from my flatpak branch. Fixes an edge case issue where the container can be destroyed before the Idle code runs which causes issues.
=> Check if appcontainer is destroyed before updating

data/io.elementary.appcenter.service.in
Fixes #983 
Since this has to match the well-known name that the DBusServer registers on, which is hardcoded here:
https://github.com/elementary/appcenter/blob/26b60a1b572ea29a1ffed01b0330bbcb29d1ffa0/src/Services/DBusServer.vala#L21
The `DBus` annotation doesn't support using a constant here, it only supports string literals. So we can't use the `Build.PROJECT_NAME` constant from `config.vala`. Or we could use meson to reconfigure `DBusServer.vala`, but this is easier for now.
=> Use io.elementary.appcenter as dbus name

src/Core/Package.vala, src/Core/PackageKitBackend.vala
Instead of clearing out the list of packages in the backend and building it again when we reload the appstream data, we can simply replace the appstream component on the ones that already exist.
This helps with a few things where the package is already referenced in cached AppInfoViews or banners and holds the reference but a newer, updated package has come along.
=> Reuse package objects on reload

data/io.elementary.appcenter.appdata.xml.in
As indicated in the spec, this should prevent people from breaking their install by removing their means of installing apps and updates
=> AppData: Make compulsory for Pantheon

src/Core/Package.vala
Some string suggestions with the following goals in mind:
* I don't think we need to point out that AppCenter is curated. In the list view, we only point out non-curated apps.
* The word "Repository" probably doesn't mean much to regular people, and I think the distinction of "Flatpak" is probably lost as well. If someone adds a source like "Flathub" that's probably already more meaningful to them than pointing out that it's a Flatpak repo.
* I would like to point out any repo that is non-curated so that we're warning users that these apps have not been vetted.
Interested in feedback from UX team :)
=> Package: Rename repos

src/Views/AppListUpdateView.vala, src/Widgets/UpdateHeaderRow.vala
Seems kind of silly to duplicate an existing public method
=> UpdateHeaderRow: Remove duplicate public method

src/Views/AppListUpdateView.vala, src/Widgets/AbstractAppList.vala
Fixes #1009 
Previously, the OS updates package was always sorted above everything that wasn't currently updating. Therefore, if there were no OS updates, but there were separate packages that required an update, the up to date OS updates row would be above them, leaving the effect shown in the issue screenshot.
This changes the logic slightly so that OS updates are only sorted to the top under their respective header (needs update or already up to date).
There is also a minor fix to `AbstractAppList.vala` that ensures the sorting and headers are invalidated when the list box is cleared, which was causing a temporary sorting issue while the listbox was repopulated.
=> Sort OS updates more sanely

src/Views/AppInfoView.vala
It seems common that developers assume that we'll only respect line breaks from `<p>` tags and that they can maintain their own indentation in their xml files. This makes sure we strip out line breaks and extra spaces before we pass markup to appstream to be parsed. This addresses issues like #249 but for the appinfoview instead of the banner
=> AppInfoView: strip extra spaces and line breaks

src/Application.vala
As per https://www.iana.org/assignments/media-types/media-types.xhtml
(It should have been MIME type, so an error is avoided here.)
Similarly: https://github.com/elementary/files/pull/978
=> Spelling: mimetype → media type

data/styles/application.css, src/Widgets/AppContainers/AbstractAppContainer.vala, src/Widgets/HumbleButton.vala
Prevent an issue where `h3` styles were being applied in the updates view
Before:
After:
=> Move banner button text size to prevent leakage

src/Widgets/AppContainers/AbstractPackageRowGrid.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala
=> Fix release info wrapping

src/Core/UbuntuDriversBackend.vala
This greatly improves issue #975 by keeping a cache of compatible Ubuntu drivers. It takes a while to discover the drivers and associate them to Package objects so doing this each time the installed list needs to load causes it to show the placeholder message for much longer than it needs to.
There will still be a bit of a delay loading the list on a completely cold start, but if AppCenter is running silently in the background (like it normally is), the loading of the installed list should be pretty instant again after opening it.
=> Cache list of Ubuntu driver packages

src/Core/FlatpakBackend.vala
We're using the concept of flatpak transactions to install and update packages as this allows the dependency runtimes to be installed with the package and allows multiple packages to be updated at once.
The API allows us to decide whether to continue working on other packages in a transaction when an error is caught. I think I previously had the logic a bit backwards here, so this PR fixes and clarifies this.
=> Better flatpak transaction error handling

src/Widgets/AppContainers/AbstractAppContainer.vala
The required margin (12px) is already applied in AbstractPackageRowGrid.vala (margin_end).
Fixes #1008.
=> Fix misaligned Update All button.

po/POTFILES, src/Core/Package.vala, src/Views/AppInfoView.vala, src/Views/AppListUpdateView.vala, src/Widgets/SizeLabel.vala, src/Widgets/UpdateHeaderRow.vala, src/meson.build
=> Add info icon and tooltip for download size

data/io.elementary.appcenter.gresource.xml, data/styles/application.css, data/styles/arrow.css, src/Views/AppInfoView.vala
* For things that overlay, a semi-transparent box shadow usually looks cleaner than a border
* Inner highlights to match other widgets
* Also apply the clicked style to :disabled buttons
* move arrow CSS to its own file and add the provider directly to the button context so we make sure we don't leak this .arrow class anywhere else on accident
=> Move arrow CSS to its own file and adjust

data/io.elementary.appcenter.gresource.xml, data/styles/application.css, data/styles/arrow.css, src/Views/AppInfoView.vala, src/Widgets/Switcher.vala
Show previous/next arrows to control the screenshots on hover:
Fixes #365.
=> Add prev/next arrows for screenshots

data/io.elementary.appcenter.gresource.xml, data/styles/loading.css, src/Views/AppInfoView.vala
Inspired by #1050, using the sort of shine placeholder animation that's become common on the web and in apps like Slack. If we think it's clear enough that it's loading, we could even remove the spinner altogether.
=> Animate screenshot background while loading

src/Widgets/AppContainers/AbstractAppContainer.vala
Instead of packing an empty child, use Gtk.Revealer for its intended purpose and set a transition that doesn't reserve space
=> Abstractappcontainer no stack hacks

data/io.elementary.appcenter.desktop.in.in
Currently when you search for "Updates" in the applications menu you get:
This gives you less one fewer option and would ideally be better if we sorted app actions higher:
Also sets an icon so that will show up when we fix that in the applications menu
=> Desktop: Add icon to updates and remove keyword

src/Core/FlatpakBackend.vala, vapi/flatpak.vapi
I ran into #1086 while installing Steam, which also failed due to openh264:
> FlatpakBackend.vala:613: Flatpak installation failed: runtime/org.freedesktop.Platform.openh264/x86_64/19.08 needs a later flatpak version (1.4.2;1.2.5;1.0.9;)
It turns out the error callback lets us know if an error is fatal, and we can ignore non-fatal errors. This change allowed me to install Celluloid.
=> Fix #1086 by ignoring non-fatal Flatpak errors

src/Core/FlatpakBackend.vala
While developing Sideload, we discussed that AppCenter and Sideload should both install and manage user-specific Flatpaks by default and then we'd have some form of checkbox or something to install systemwide if necessary.
This is sort of a breaking change (to a not yet released version of AppCenter) since it will no longer be able to see or update systemwide installed Flatpak applications, but it shouldn't be too hard to add that functionality in. I'd just rather get this change in first so I can start to bring this back into sync with the work I've been doing in Sideload.
=> flatpak: Work with user-specific flatpaks by default

src/Core/FlatpakBackend.vala
Fixes #1026 
Take one of the recent commits from Sideload and apply it here. Instead of the progress bar going from 0-100 for each operation within a transaction, divide it up and work out how we can go from 0-100 over the full transaction.
=> flatpak: Track overall transaction progress

src/Widgets/CategoryFlowBox.vala
This is the right icon name for this context since this is the icon name for the office category.
If we want to change the metaphor of this icon that should be done in the icon theme, not by using an icon name from the mimes context
=> CategoryFlowBox: use correct icon for office category

src/AsyncMutex.vala, src/Core/BackendAggregator.vala, src/Core/UbuntuDriversBackend.vala
Fixes a lint error about a blank line at the end of a file and fixes a few warnings about not being able to copy delegates (so transfer them as owned).
=> Fix lint error and delegate warnings

src/Core/Package.vala
The new unreleased `appstream-data-pantheon` package now has a metadata bundle with an origin of `elementary-stable-{series}-main` instead of just `stable-{series}-main` which seemed a bit too generic and had the potential for conflicts. We need to update AppCenter to be aware of this new origin before releasing the new appdata package or elementary applications will appear as non-curated.
I've also removed the daily origin here because as far as I can tell, we never had a package origin called `daily-bionic-main`. The origin refers to the AppStream origin and we never had any daily AppStream data being generated or installed. I suspect that packages from the daily repos will just fall under the stable metadata. Though this is worth testing by someone running with the daily PPA.
=> Use new orign name from appstream data

data/io.elementary.appcenter.appdata.xml.in, src/Core/BackendAggregator.vala
Instead of iterating through all backends when they don't necessarily have updates. Only call the update method on the ones that have updates listed in `change_information`.
This may improve issues like #1119 but I'm struggling to reproduce it consistently. Either way, this should at least be a minor efficiency improvement.
=> Only call update on backends which have updates available

data/io.elementary.appcenter.service.in, data/meson.build
Fixes #1063
This prevents AppCenter from being able to be launched by DBus.
Rationale:
- The AppCenter daemon autostarts anyway with its autostart file, and the applications menu watches the bus and connects/reconnects as necessary when it starts/restarts. We might opt to reduce the autostart delay down from 60 seconds, so it's ready for the applications menu sooner.
- Having this service file makes it even more difficult to stop AppCenter autostarting. Even if you remove the autostart file, it will still start every time you open the applications menu. There are people that like to disable the autostart for various reasons (bandwidth, CPU load, etc...)
- This is the cause of the AppCenter window opening on startup that's being reported a lot at the moment. If you've opened the …
=> Remove dbus service file

debian/appcenter.install, debian/rules
Follow up to #1126 to remove the dbus service file from packaging.
=> deb-packaging: remove dbus service install

data/io.elementary.appcenter.appdata.xml.in, src/Core/PackageKitBackend.vala, src/Views/InstalledView.vala
I've noticed that since merging the speedups for the homepage, the installed view seems to be loading one package at a time quite slowly. I've applied the same parallel learnings to that page so that everything loads in much quicker.
=> Lookup PackageKit packages for the installed view in parallel

src/Views/AppInfoView.vala
* Version numbers are largely meaningless. Packages are assumed to be the latest version, whatever that is, unless we warn otherwise.
* If someone really needs to see the version number they can scroll down to "What's New" and see it there
* We already show the version number on the updates view where it might matter to someone
=> AppInfoView: Remove version from header

src/Core/FlatpakBackend.vala
This should monitor the FlatpakInstallation for any changes, and if it finds some, trigger a cache refresh to update the UI accordingly. This will allow changes to propagate if a remote is modified/added/removed without needing to restart AppCenter.
fixes #1198
=> Monitor FlatpakInstallation for Changes

data/io.elementary.appcenter.appdata.xml.in, src/Views/AppInfoView.vala
Instead of always downloading the largest (original) size image, save a bit of bandwidth (especially on LoDPI) by choosing the image that is closest to the width it will be displayed at.
This is related to #1104 but doesn't necessarily completely solve it.
=> Choose a more appropriate screenshot size to download

data/io.elementary.appcenter.appdata.xml.in, src/Views/AppListView.vala
If the compare function was comparing two elementary native applications, it would be kind of random as to which one would come out on top.
Ensure we use lower sorting criteria (alphabetical) if both apps are native.
=> Fix sorting of native apps in list views

data/io.elementary.appcenter.appdata.xml.in, src/Core/FlatpakBackend.vala, src/Core/PackageKitBackend.vala
Fixes #1114 
We were assuming that if there were components that already existed on a `AppStream.Category` object that we could re-use them. These could be out of date or from another backend, so best to clear this list and regenerate every time it's queried.
=> Ensure categories are cleared of cached components before querying

data/io.elementary.appcenter.appdata.xml.in, src/Core/FlatpakBackend.vala
Fixes #1072 
Allows us to track the installed state of flatpaks that are being changed outside of AppCenter, which makes the "Uninstall" action in the applications menu context menu work properly.
=> FlatpakBackend: Update installed applications on external change

BACKERS.md
Also made it a bulleted list instead of code style. "Anonymous Backer" is someone who chose to back at a "Name in Source Code" level, but chose to keep their contribution anonymous. We'll want to get their permission before exposing their names.
=> BACKERS.md: Add AppCenter for Everyone backers

data/styles/arrow.css
Instead, use `@textColorPrimary` so it remains contrasty with the `@base_color`. Fixes unreadable arrows when using a dark style.
=> arrow.css: Don't hardcode arrow color

data/io.elementary.appcenter.appdata.xml.in, src/Core/BackendAggregator.vala, src/SuspendControl.vala, src/Views/AppListUpdateView.vala
Fixes #1253 
The backends can transition rapidly from working to not working between operations, so we wait for 5 seconds of no activity before removing the inhibitor.
Also fix the app ID while we're here.
=> Inhibit suspend during all package operations

data/io.elementary.appcenter.appdata.xml.in, meson.build
https://github.com/elementary/appcenter/compare/3.2.3...release-3.2.4
I know this was recently released, but this fixes a super annoying crash when installing updates.
User-facing:
- Prevent crashes when updating Flatpaks and system packages simultaneously (#1246)
- Prevent suspending when installing, updating, or removing packages (#1255)
- Updated translations
Also adds debugging to further clean up the Updates tab (#1252)
=> Release 3.2.4

data/io.elementary.appcenter.appdata.xml.in, src/Views/AppInfoView.vala
Currently clicking on a plugin on an app info view does nothing. Now we browse to the app info view for that plugin.
This is quite slow for switchboard plugs due to them not having a description field in the appdata and us falling back to fetching that information from packagekit when it's not available from appstream.
=> AppInfoView: allow opening plugins

data/io.elementary.appcenter.appdata.xml.in, src/Views/AppInfoView.vala
I've noticed that if a given package doesn't have a description set in appdata (Switchboard plugs seem to be a good example) we fall back to loading this from the backend. For packages that come from PackageKit, this is pretty slow (especially if we're refreshing updates too). 
This was causing a hang when clicking on these apps. But if we move this into the `load_more_content` method, we get to the page instantly and then that data pops in afterwards.
=> AppInfoView: load description async

src/Views/AppInfoView.vala
The `AppStream.markup_convert_simple` was the only part that needed the try/catch.
I added some more details to the error and made it not critical while I was here.
=> AppInfoView: parse_description reduce try/catch scope

data/io.elementary.appcenter.appdata.xml.in, src/Core/PackageKitBackend.vala
Fixes #508 
Even if you manage to set your proxy settings in dconf using the switchboard plug, set up `http_proxy` and `ftp_proxy` environment variables, remember to modify apt's config files to include the proxy, AppCenter still can't do any PackageKit operations behind a proxy.
This is because PackageKit does its own proxy handling and you can manually configure it in yet another config file, but we can get AppCenter to use GLib's proxy resolver which reads from the dconf keys setup by the switchboard plug and pass any relevant proxy config to PackageKit.
=> PackageKitBackend: Tell PackageKit about any system proxy config

src/Core/PackageKitBackend.vala
The `Client` class talks to all backends, including Flatpak. When things change in PackageKit, we only want to refresh our PackageKit cache, not our flatpak cache too.
=> PackageKitBackend: only refresh PK cache on changes

data/io.elementary.appcenter.appdata.xml.in, data/io.elementary.appcenter.gschema.xml, src/Application.vala, src/Core/Client.vala
Store the last refresh time in GSettings and only refresh the cache if it's been >24 hours since the last refresh. Opening the window still forces a refresh of the cache, but now at least if you start your computer multiple times in a 24 hour window, AppCenter isn't doing a cache refresh every time.
We still notify that updates are available on startup without refreshing the cache if there are some leftover from the last cache update.
I removed an unused `updating_cache` property while I was here and cleaned up some of the overly complicated setting of `refresh_in_progress`
Finally, I've ensured the next refresh gets scheduled from 24 hours after the last refresh, rather than 24 hours from when AppCenter started. Meaning if your computer starts 23 hours after the last cache refresh, …
=> Prevent the daemon refreshing on every startup

data/io.elementary.appcenter.appdata.xml.in
It was getting a bit unwieldy. 
- Categorize them under performance, extensions, keyboard, fixes, and more
- Consistently use "extension" instead of plugin (since that's what it says in the UI)
- "computer" → "device"
How it looks in AppCenter:
=> AppData: Organize 3.2.5 release notes

src/Core/Package.vala, src/Views/AppListUpdateView.vala, src/Views/AppListView.vala
Fixes #1275 
Hide them from category and search views and only show them in the installed/updates view if they need an update.
=> Hide fonts unless they need an update

src/Core/Houston.vala
Reduce the time we wait for Houston to respond down from the default of 60 seconds to 15.
Handle the case where Houston doesn't respond at all within that timeout by handling a null response.
=> Better handle Houston errors

po/POTFILES, src/Application.vala, src/Dialogs/InstallFailDialog.vala, src/meson.build
Replace the dialog that appears when an app fails to install that looks like this:
With one that looks like this:
=> Improve installation failure dialog

src/Core/Package.vala
Fixes a minor regression noticed since the recent performance improvements. While AppCenter is initially starting up, if you're looking at the installed tab, you briefly see that some of these apps have a "Free"/"Install" button until loaded fully.
Since we know these apps are installed, we need to make sure that state is consistent while loading.
=> Refresh state after marking package installed

data/io.elementary.appcenter.appdata.xml.in, data/io.elementary.appcenter.gschema.xml, meson.build, meson_options.txt, src/Core/Houston.vala, src/config.vala.in
Fixes #476
Fixes #210 
Make the API base URL configurable via meson so this can be changed in packaging by downstreams (like System76) if desired.
On a successful fetch of app lists from the API, store the result in GSettings so if we have any subsequent failures, we can use the cached list instead.
I've opted to use a GSettings dictionary rather than specific settings for e.g. most downloaded, most recent. The key used in the dictionary is the API endpoint path, so again if these are changed downstream, the caching will still work.
I've put some blank dictionary entries in the default field of the schema file so there's an example of the syntax that will help downstreams write a list of apps in here manually if they wish.
Edit: As another note, it would have been simpler in terms of code …
=> Cache Houston API results to GSettings

.github/workflows/main.yml, data/io.elementary.appcenter.appdata.xml.in, data/io.elementary.appcenter.policy.in, data/meson.build, meson.build, po/extra/POTFILES, src/Core/PackageKitBackend.vala
This is part of our recent decisions in #465 and it allows PackageKit/apt packages to be updated without throwing a password dialog.
@cassidyjames I'm still debating in my own head whether it's a good idea to allow systemwide Flatpaks to be installed without auth for the following reasons:
1. It's then inconsistent with PackageKit packages. We need a password to install a package from an apt repo systemwide. Why are Flatpaks special? I understand an admin has to have jumped through the hoops of adding the remote intially.
2. But, Flatpaks _could_ be just as dangerous as debian packages in theory and we're going to allow any other non-admins (children?) on the machine to just install them systemwide?
3. I think initially we thought Flatpak might not have granular enough permissions to …
=> Add polkit action to allow updates without admin prompt

po/extra/tr.po, src/Application.vala, src/Core/Client.vala
Use `yield` syntax on the calls to Granite so we wait for one to finish before we start another and wrap the method in an `AsyncMutex` to make sure that there aren't any race conditions on `updates_number` where it gets updated in between Granite method calls.
I think this should probably fix issues where people are seeing incorrect/zero counts on the badge, but since I've never been able to reproduce that issue, I can't confirm for sure.
=> Various update badge fixes

src/Views/AppInfoView.vala
Don't set h3 on buttons because we control text size and weight in the banner CSS already so this does nothing.
=> AppInfoView: Don't set h3

src/Views/AppInfoView.vala, src/Views/AppListUpdateView.vala, src/Views/AppListView.vala, src/Widgets/AppContainers/AbstractPackageRowGrid.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala, src/Widgets/AppContainers/ListPackageRowGrid.vala, src/Widgets/PackageRow.vala
* Every place we use this row, we set `show_uninstall` to false
* `info_size_group` is never used for `PackageRow.list`
* Don't add uninstall to the group because we never use it
=> AbstractPackageRowGrid: Reduce args where possible

src/Widgets/AppContainers/AbstractAppContainer.vala, src/Widgets/AppContainers/AbstractPackageRowGrid.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala
Trying to cut down on the UI code in AbstractAppContainer. Making it a `Bin` forces subclasses to lay out their own grids
=> AbstractAppContainer: Subclass bin

src/Views/AppListUpdateView.vala, src/Views/AppListView.vala, src/Views/InstalledView.vala, src/Views/SearchView.vala, src/Widgets/AbstractAppList.vala
* `loading_view` is only ever used in `AppListUpdateView` so it should go there
* The copy for `alert_view` is specific to search, so it should go to `AppListView` (for now, because category and search views use the same app list)
* I removed the placeholder switching from the installed view because it shouldn't theoretically be possible to have absolutely zero packages installed. You're always going to at least have AppCenter. And if it were possible, the copy is wrong anyways
=> AbstractAppList: move placeholders to subclasses

src/Views/AppListView.vala, src/Views/SearchView.vala
Search order is defined by the search_priority function. This takes the lowercase application name and lowercase search term, and sorts with the following order:
- Name starts with term
- Name contains term
- Name does not contain term
Fixes https://github.com/pop-os/shop/issues/171 and is a good start on https://github.com/elementary/appcenter/issues/1279
=> Sort search view using search term

src/Widgets/AbstractAppList.vala, src/Widgets/AppListRow.vala, src/Widgets/PackageRow.vala
Not sure why this existed historically, but since `PackageRow` is the only class that implements `AppListRow` and it hardcodes the result to `true`, this property is useless
=> AppListRow: Remove unused has_package

src/Utils.vala, src/Views/AppListUpdateView.vala
I'd prefer to keep code that depends on GUI classes out of `Utils.vala`
=> Move single-use reboot method out of utils

src/Core/Client.vala
Make sure we're RDNNing our notification ID so we don't conflict with anybody else
=> Client: Use RDNN for notification ID

README.md
Fixes #1339.
This just documents a required build dependency. 🤗
=> Document the libpolkit-gobject-1-dev build dependency

src/Widgets/AppContainers/AbstractPackageRowGrid.vala
So that subclasses also set these properties without having to call `base()`
=> AbstractPackageRowGrid: Set default properties in construct block

src/Core/FlatpakBackend.vala, src/Core/Package.vala, src/Core/PackageKitBackend.vala, src/Core/UbuntuDriversBackend.vala, src/Views/AppListUpdateView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala
This takes some of the work from #1319 and breaks it into its own PR.
This is quite an important first step in some refactoring/optimizations that start to unblock some of the work of prioritizing different package sources and enabling systemwide flatpak support.
This should bring about no functionality changes to make testing easier.
In summary, the changes are:
* Only update the flatpak cache if changes weren't triggered by AppCenter. We were previously picking up on the `changed` signal for stuff that was being changed in AppCenter which is unnecessary.
* Refresh the installed/updatable state of applications when external changes happen (i.e. CLI tools)
* Never query the backend synchronously for the installed state of an application. Check once at startup and then try to keep it up to …
=> Installed state optimisations

src/Views/AppListUpdateView.vala, src/Widgets/UpdateHeaderRow.vala
I'd forgotten we had a little spinner header in the installed/updates view, but it's been broken for a while, so this PR removes the associated code. When it worked, it looked something like this:
=> Remove broken spinner in update view header

meson.build, src/Core/ScreenshotCache.vala
`file_info_get_modification_date_time` was added in GLib 2.62. We need to put a conditional compile in to allow this to continue compiling on bionic which we still want to support for now.
=> ScreenshotCache: support older GLib

src/Views/AppInfoView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala
We shouldn't be using `replace` to remove `".desktop"` from the component ID, which could remove `".desktop"` from the middle of a string:
(`com.github.spheras.desktopfolder -> com.github.spherasfolder` :scream: )
We should be only removing it from the end of the string. Luckily we already have a pre-built property for this in the `Package` class :wink:
=> Don't replace .desktop in component ID

data/io.elementary.appcenter.appdata.xml.in, src/MainWindow.vala
Fixes an issue where AppCenter would reopen at a different position than the last saved.
We need to make sure we construct the UI before trying to restore size and position, otherwise the window can resize after the restore and we get faulty coordinates. This makes the window move slightly every time we restore until eventually it's opening off in some corner of the display
=> MainWindow: Restore window size and position last

src/Core/FlatpakBackend.vala
Fixes part of #1403 (The names are still not displayed correctly, but they are updated now)
It turns out if you invert your booleans and don't actually tell flatpak to update any packages, things go a bit awry when you try to update flatpak packages.
I have no idea who wrote this code originally. Hint: *it definitely wasn't me* :grimacing:
=> FlatpakBackend: Fix stuck updates issue

src/Views/AppListView.vala
Instead of doing `string.has_prefix` and `string.contains`, we can do `string.index_of` and use the result to figure out the answer to both. 
If the needle is at the start, it's as fast as `has_prefix`, if it's not in the string, it's as slow as `contains` but this means we're doing slightly less expensive string operations in some cases. It probably doesn't save much, but for some reason I had this idea rattling around in my head as I was falling asleep, so I had to open a quick PR and clear my conscience... :sleeping:
=> Optimise search rank algorithm

src/Core/FlatpakBackend.vala, src/Core/UpdateManager.vala
=> Correctly display names of flatpak runtimes in OS updates

data/io.elementary.appcenter.appdata.xml.in, meson.build
Fixes the Flatpak runtime name issue.
https://github.com/elementary/appcenter/compare/3.5.0...release-3.5.1
=> Release 3.5.1

data/io.elementary.appcenter.appdata.xml.in
From a comment on weblate: https://l10n.elementary.io/translate/appcenter/extra/ja/?checksum=eb8d0607429487d2#comments
=> AppData: Fix a typo "beeen" to "been"

README.md
It looks like a5a7f2b updated `meson.build` in this way.
=> README.md: List libhandy dependency as libhandy-1-dev

src/Application.vala
Related to #1456, see https://github.com/elementary/sideload/pull/101 and https://github.com/elementary/sideload/pull/102
=> Application: "successfully" is redundant

src/Views/AbstractView.vala
Fixes #1482 
Seems safest to revert for now until we can find the source of the issue with Deck
=> AbstractView: Use Gtk.Stack instead of Hdy.Deck

data/io.elementary.appcenter-daemon.desktop.in, data/io.elementary.appcenter.desktop.in.in, meson.build, meson_options.txt, src/Application.vala, src/Core/Client.vala, src/Core/UpdateManager.vala, src/Dialogs/StripeDialog.vala, src/MainWindow.vala, src/Widgets/Banner.vala
This just seems less error-prone since we're using the same string over and over again. We name the icons from the Meson project name to begin with, so let's ensure we're requesting the exact icons by using the same Meson variable.
=> Use Meson project name for icons

src/Core/PackageKitBackend.vala
`client.search_names_sync` may get a package that isn't an exact match. In testing on Pop!_OS, we noticed the `peek` package was incorrectly marked as uninstalled with the latest AppCenter.
It seems instead of `peek`, `client.search_names_sync` was getting `cardpeek` as the first result (just as `apt search peek` does).
This seems to be the correct function for this purpose.
=> Use `client.resolve_sync` in `get_package_internal`

src/Core/FlatpakBackend.vala, src/Core/PackageKitBackend.vala
```shell
../src/Core/FlatpakBackend.vala:289.53-289.57: error: Assignment: Cannot convert from `GLib.GenericArray<AppStream.Component>' to `GLib.GenericArray<weak AppStream.Component>?'
GLib.GenericArray<weak AppStream.Component> comps = user_appstream_pool.search (query);
^^^^^
../src/Core/PackageKitBackend.vala:396.53-396.57: error: Assignment: Cannot convert from `GLib.GenericArray<AppStream.Component>' to `GLib.GenericArray<weak AppStream.Component>?'
GLib.GenericArray<weak AppStream.Component> comps = appstream_pool.search (query);
```
=> Allow build with appstream 0.14.x

src/MainWindow.vala
In https://github.com/elementary/appcenter/pull/1456 we added support to throw a toast when an app is installed.
Sometimes opening the application fails. For now this adds a dialog showing an error message.
Fixes https://github.com/elementary/appcenter/issues/1494
=> Throw a dialog on failure when trying to open an installed app

src/Core/ScreenshotCache.vala
Fixes #1537 
Same fix as merged downstream in PopShop https://github.com/pop-os/shop/pull/271
workaround for https://github.com/elementary/flatpak-platform/issues/34 as well
=> ScreenshotCache: don't bail if modified time is null

src/Core/FlatpakBackend.vala
Fixes #1555
It's a bit of a hacky workaround since it's not really AppCenter's problem that whatever is generating the collection metadata isn't being standards compliant, but it's a workaround that gets us out of a hole quickly if we want it.
=> Remap AppStream 'metadata' tag to 'custom'

src/Core/Package.vala
Now that we have appstream data for focal building in the stable PPA, we can change `bionic` -> `focal`
I've also removed the deprecated origin while I was here.
=> Fixup package origins for focal

src/Views/AppInfoView.vala
`size_label` has an instance only when the package is loaded from local:
https://github.com/elementary/appcenter/blob/dfb5ecd641d1214a67cf7909423400a3894799bb/src/Views/AppInfoView.vala#L367-L376
So we need to make sure it's not null before calling `size_label.update ()`; you should get the following warning message when you load local package with the latest master branch:
```
** (io.elementary.appcenter:45910): CRITICAL **: 21:39:33.842: app_center_widgets_size_label_update: assertion 'self != NULL' failed
```
=> AppInfoView: Don't try to update size info in case of local packages

data/io.elementary.appcenter.appdata.xml.in, src/Application.vala
=> Application: Fix open button in toasts

src/Widgets/AppContainers/AbstractAppContainer.vala, src/Widgets/PackageRow.vala
Only ever used once outside this class and `package` is publicly available so it's not really necessary
=> AbstractAppContainer: Remove is_os_updates property

meson.build, src/Application.vala, src/config.vala.in
Provides the directory where the locales are actually installed.
We are [packaging this](https://github.com/NixOS/nixpkgs/pull/130380#issuecomment-895720580) in NixOS, and due to NixOS 's special `localedir`, we cannot apply the translations without this patch.
Thanks in advance for reviewing this :-)
=> l10n: Correctly setup the locales

src/Core/FlatpakBackend.vala
Fixes #1585 
Ensure that the user installation is pre-selected when clicking on items on the homepage. Also did a bit of optimization of the package lookup loops while I was here. All packages from the user and system installations are already in the `package_list` collection, so no need to iterate over both separately.
=> Sort user installation first on homepage

src/Core/Job.vala, src/Core/PackageKitBackend.vala, src/Core/UbuntuDriversBackend.vala
Fixes #1603 
As described in the linked issue report, the `bcmwl-kernel-source` module and probably other Ubuntu driver packages, only depend on the non-HWE kernel headers.
As they are dkms drivers, they have to compile the driver from source against a set of kernel headers that match the running kernel. On elementary and HWE Ubuntu, installing one of these drivers via any means (AppCenter/`apt`/`ubuntu-drivers`) pulls in the headers for the non-HWE kernel and if you don't already have the HWE headers installed by some other means, the module doesn't get compiled for your running kernel and you're left confused because you installed the driver but it doesn't work.
This checks if a driver to be installed depends on `dkms`. If so, we know it needs headers, so we add the correct header …
=> Drivers: Ensure headers are installed for dkms drivers

src/Core/FlatpakBackend.vala
Basically the same as https://github.com/elementary/sideload/pull/132/files
Should allow us to save some bandwidth/space by using the runtimes from the system installation for user installs. Means the first app install from the AppCenter remote will be a few MBs at most instead of a few MBs plus the elementary runtime.
=> FlatpakBackend: add default deps sources to transactions

data/icons/categories.gresource.xml, data/icons/oars/social-info.svg, src/Views/AppInfoView.vala
* Show descriptions for OARS ratings in a label rather than a tooltip
* Break out `social-info` into its own item with specific descriptions for each level
=> Oars socialinfo

src/Views/AppInfoView.vala
Follow-up to #1683. If AppCenter is compiled with `-Dcurated=false` it doesn't make sense to show this badge.
=> AppInfoView: only show non-curated badge when using `curated` flag

src/Views/Homepage.vala
One way of fixing #1665. This simply stops the page from scrolling horizontally, which will force the window to fit its contents. It fixes the visual weirdness so is a first step, but the root cause is that three-wide in the recently updated flowbox is too wide at smaller sizes.
However, setting the flowbox's minimum to 2 makes the children expand to a weirdly wide size, so I don't know if that's what we want to do or if there's something smarter to be done. Regardless, this is probably a good first step.
Renamed the `category_scrolled` while I was here because it's not just for the categories, it's for the whole homepage and that was confusingly named when I was first investigating it. :) Alternatively could name it `homepage_scrolled` if that's more clear.
=> Homepage: don't horizontally scroll

src/Views/AbstractView.vala, src/Views/AppInfoView.vala
Sometimes I've experienced an issue where the method is trying to pack widgets into the carousel before it's completely constructed so we get warnings about how the toplevel container can't hold more than one widget
I'm not sure why this is a timeout waiting for the end of the transition and why we're passing in the cache from `AbstractView`. Is there a significant difference between this and connected to `realize`?
=> AppInfoView: load_more_content on realize

data/io.elementary.appcenter.appdata.xml.in, src/MainWindow.vala, src/Views/AppInfoView.vala, src/Views/AppListUpdateView.vala, src/Views/Homepage.vala, src/Widgets/AbstractAppList.vala, src/Widgets/AppContainers/AbstractAppContainer.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala, src/Widgets/AppContainers/ListPackageRowGrid.vala, src/Widgets/CategoryFlowBox.vala, src/Widgets/PackageRow.vala
Supersedes #1742
* MainWindow: change size request to default size
* AppInfoView, Homepage, CategoryFlowbox: Remove minimum flowbox child number
* AbstractAppContainer.vala: Remove actionstack hexpand to allow name and summary labels to fill width
* InstalledPackageRowGrid:
* create infosizegroup here instead of passing it through multiple constructors
* Add hexpand back to actionstack here since we need it to left align expanders which don't preserve width for hidden children
ListPackageRowGrid: expand labels and let them wrap
=> Allow narrower window sizes

src/Views/AppListUpdateView.vala, src/Views/AppListView.vala, src/Widgets/AbstractAppList.vala
* `construct_row_for_package` is never called in the abstract class and it does a different one-liner in each implementation
* Replace `add_row` with connecting to `ListBox.add` so we make sure these things actually happen any time a widget is added to the list and not just when this special function is called
* `on_list_changed ()` only ever calls `invalidate_sort ()`, so just do that directly instead
=> AbstractAppList: Remove unnecessary abstractions

src/Core/Job.vala, src/Core/PackageKitBackend.vala
We can pass `null` to `get_updates`, so ensure we reflect that with a nullable.
Also mark the cancellables as nullable in the args containers for the methods where we can pass null.
=> PackagekitBackend: Make nullable state of cancellables consistent

src/Views/AppListView.vala, src/Views/SearchView.vala
AppCenter refers to a FlatHub Link (https://flathub.org) if no apps match the search term.
This pull request dynamically changes the URL with the currently searched term in the text box.
On Search `filez` in the Search Box, if no apps match the Link for the FlatHub URL becomes https://flathub.org/apps/search/filez instead of the static https://flathub.org
Until at least one app is installed by Side-loading from FlatHub, AppCenter does not load them automatically. It is convenient for users to click the link and directly navigate to the FlatHub App Search Page instead of Navigating through the FlatHub Website for Searching the App of their need.
=> Dynamic Links to FlatHub

src/Core/BackendAggregator.vala, src/Core/BackendInterface.vala, src/Core/ChangeInformation.vala, src/Core/FlatpakBackend.vala, src/Core/Job.vala, src/Core/Package.vala, src/Core/PackageKitBackend.vala, src/Core/UbuntuDriversBackend.vala
Allows to make sure that we are safe regarding the lifetime of the ChangeInformation
and allows to pass it safely to multiple closures.
=> Core: Pass the ChangeInformation object around instead of its callback

src/MainWindow.vala, src/Views/Homepage.vala
The use of notify on external objects and of timeout actually increases the reference of the object, try to release it on-demand.
=> Avoid multiple circular references

src/MainWindow.vala
Fixes #1808 
* Always update when the stack changes views, not just when special view switching methods are called
* View switcher only updates the stack now
* Programmatically change views directly with the stack, not via the view switcher
* Put the badge eventbox outside the revealer so it doesn't swallow clicks
Might make view switching more reliable, makes it easier to replace the view switcher for Gtk4
=> MainWindow: Reliably update on view change

src/Core/Client.vala, src/Core/UpdateManager.vala, src/MainWindow.vala
Fixes #1833
* Make copy more clear that this is for app updates only, not operating system updates
* Notify for unpaid apps, and don't recheck settings on every loop
=> Client: auto update non-native apps

src/Widgets/AppContainers/AbstractAppContainer.vala, src/Widgets/HumbleButton.vala
AbstractAppContainer is kind of a lame class that only really exists to add more things to HumbleButton, so we should probably just move those things to HumbleButton since there are no instances of it that don't use these additional things.
Start that by moving the stripe dialog here
=> HumbleButton: move show_stripe_dialog here

src/Views/AppInfoView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala
This is leftover from when there used to be a separate progressbar from the cancel button
=> AbstractAppContainer: Remove progress_grid

src/Core/PackageKitBackend.vala
Fixes #1849 
Verify this by opening AppCenter to Accessories and seeing if apps like "0Install" appear. Also check that non-Flatpak elementary apps like Photos still appear
=> PackageKitBackend: don't load Ubuntu components with AppStream 0.15

src/Views/AppInfoView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala, src/Widgets/AppContainers/AbstractPackageRowGrid.vala
Uninstall buttons are only ever shown in the AppInfo view, so move it here
=> AppInfoView: move uninstall button here

src/Views/AbstractView.vala
This prevents a second click on e.g. the banner or a recently updated item on the Home Page from loading duplicate views.
=> Do not show another package before transition complete

src/Views/AppInfoView.vala
Fixes #1864 
Wrapping is better for localization and responsive. We want to be able to see the whole app title on the app info view
=> AppInfoView: Wrap package_name instead of ellipsize

src/Views/Homepage.vala
Looks like this dead code was accidentally left in when merging #1769
=> Homepage: remove dead currently_viewed_category

data/io.elementary.appcenter.gresource.xml, data/styles/Screenshot.css, src/Views/AppInfoView.vala
Add an accent colored background behind screenshots and display the screenshot caption
* Makes screenshot captions more obvious instead of being hidden in a tooltip
* Better exposes off-screen screenshots
* Makes the draggable area more obvious
* Style "Screenshot not available" text so that the white space preserved looks less awkward"
=> AppInfoView: Add background and caption to screenshots

src/Core/Package.vala, src/Views/AppInfoView.vala
Get brand color from AppStream and fall back to our custom key if it's not available. Also remove now unused text color method
=> Package: get branding from appstream

data/io.elementary.appcenter.gschema.xml, src/Dialogs/InstallFailDialog.vala, src/Dialogs/UninstallConfirmDialog.vala, src/Dialogs/UninstallFailDialog.vala, src/MainWindow.vala
Since we can't position the window anymore in Wayland/Gtk4 might as well get rid of this now
=> MainWindow: remove window position code

src/Views/AppInfoView.vala
Use a flowbox so we don't get unreadable labels at small sizes. While we're here, use Gtk.show_uri_on_window to avoid focus stealing prevention
=> AppInfoView: use a flowbox for links

src/Core/Package.vala
`is_native` is kind of a roundabout way of checking package origin, and `is_os_updates` would always be false for the `APPCENTER` origin, so just check that
=> Package: use AppCenter origin in should_pay

src/Widgets/SharePopover.vala
* Bump copyright
* Code style
* Since these are all `image-button` they don't also need `flat`
* construct the email button all at once
* DRY uri showing and use Gtk.show_uri_on_window to avoid focus stealing prevention
* animate with `popdown` instead of `hide`
=> SharePopover: code style and DRY

src/Application.vala, src/MainWindow.vala, src/Services/DBusServer.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala
`dialog.run ()` and `show_all ()` no longer exist in Gtk 4. Can be rebase merged
Application: you can see InstallFailDialog already connects its response to `destroy ()`
InstalledPackageRowGrid: use a Granite.Dialog instead of a Hdy.Window. Don't know why it wasn't this way in the first place. Brain must have fell out of my head :upside_down_face: Saves a few lines and window type hints aren't available in Gtk 4 anyways
=> Dialogs: use present and connect to response

src/Views/CategoryView.vala
Want to make sure we don't have to override `append` actually because we need to use it during `construct`. This simplifies things anyways because we don't need to construct the package row in `populate` because it's only used in the flowbox
=> CategoryView: change append to add_package

src/Views/AppListUpdateView.vala, src/Views/SearchView.vala, src/Widgets/AbstractAppList.vala
Can't connect to `add` in Gtk 4, so just make sure we do these things when we add
=> AbstractAppList: Remove list.add connect

data/styles/categories.css, src/Views/Homepage.vala
Reduces diff for Gtk4 a bit:
* Don't add an empty image widget to category cards with no icon
* Use calc to avoid rounding errors
* Set card padding and margin in CSS to make our lives a little simpler
=> Homepage categories

src/Views/AppListUpdateView.vala, src/Views/SearchView.vala, src/Widgets/AbstractAppList.vala
Neither implementation uses the abstract sort function, so remove it
=> AbstractAppList: Remove sort func

src/Core/Package.vala
In connection with https://github.com/elementary/icons/pull/1128, try to reduce need for a completely generic app icon, which is hard to represent, by using generic icons for categories of apps/packages.
Most apps in the AppCenter do supply their own icons.  The fallback generic icon is mainly used for system components, most of which are identified as a "generic" appstream component kind.  Presumably this is due to lack of information in the appdata?
A couple of component kinds have been given example icons but these are not ideal.
Another place the generic application icon is used extensively is when Files displays the contents of e.g. `usr/bin` for executables.  In that case it would be better to have an icon for a generic executable as these are not necessarily (desktop) apps.
=> Handle more componentkinds

src/Views/AppListUpdateView.vala, src/Widgets/AbstractAppList.vala
Only used in one implementation so move it from the abstract list. We have a null check with a continue here so I'm assuming this type of cast is intentional, maybe because row headers are listbox children?
=> Move get_packages from AbstractAppList to AppListUpdateView

src/Views/AppListUpdateView.vala, src/Views/SearchView.vala, src/Widgets/AbstractAppList.vala
It looks like this only thing this does is call `invalidate_sort ()`, but we already send the `changed ()` signal in `PackageRow` which automatically calls `invalidate_sort ()` on the ListBox, so it doesn't seem like there's a need to call it twice.
I tested installing a package and manually checking for updates and afaict the listbox sorts when packages change without this
=> AbstractAppList: Remove redundant package_changing

src/Core/Package.vala, src/Views/AppInfoView.vala
Fixes #1033
* Move this out of Package since it's only used in AppInfoView
* Use foreach functions to simplify
* Actually show up to 5 releases since the installed version
* Handle the case where the installed package is newer than the latest release info (such as in daily)
* Remove a redundant null check
=> AppInfoView: get newest releases in this class

src/Application.vala, src/Dialogs/InstallFailDialog.vala, src/Dialogs/UninstallFailDialog.vala, src/Services/DBusServer.vala, src/Views/AppInfoView.vala
These error dialogs will cause the appcenter to crash from a memory safety violation if there's a dependency conflict or network error. It seems that `show_error_details (error.message)` is consistently given an error whose `message` has already been freed. This change will take the message string into the object initialization to ensure the string survives. Dialogs are only using the string anyway.
Can be easily replicated by editing the `/etc/hosts` file and setting the apt repository to localhost.
=> fix: Segfault from error message being freed in dialogs

src/Core/Package.vala, src/Core/UpdateManager.vala, src/Views/AppInfoView.vala, src/Views/AppListUpdateView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala, src/Widgets/AppContainers/AbstractPackageRowGrid.vala
In preparation for https://github.com/elementary/appcenter/pull/1943 and potentially for https://github.com/elementary/os/pull/582, I propose that we remove updates for Flatpak Runtimes from the "Operating System Updates" category and group them in the new "Runtime Updates" category.
This would have the advantage that "Operating System Updates" would only be managed by PackageKit. This would simplify handling and presentation for https://github.com/elementary/appcenter/pull/1943.
| Before  | After  |
|:---:|:---:|
| ![](https://user-images.githubusercontent.com/10796736/208699672-2e36b098-f43c-4609-a1c5-cf4b125f1a7d.png)  | ![](https://user-images.githubusercontent.com/10796736/208699793-c4a6bcc8-1aa2-4a77-b49f-13780128caa9.png) |
| …
=> Flatpak Runtimes

src/Core/UpdateManager.vala
Follow-up PR for https://github.com/elementary/appcenter/pull/1956.
fb9f35f3461d10856ceb46403febb166f60091a7 improves the display of size information in the overview page:
| Before  | After  |
|:---:|:---:|
|![](https://user-images.githubusercontent.com/10796736/208844056-4a0e9f81-d82a-4d6e-b507-7d4e0e67171c.png)  | ![](https://user-images.githubusercontent.com/10796736/208844076-47a84ae7-140e-4aad-ac8e-d962fd3e74d0.png) |
92014a5006c40cb44a8fff07d5a0bacd4a6fb401 ensures that size information is displayed in the details page for Runtime Updates:
| Before  | After  |
|:---:|:---:|
|![](https://user-images.githubusercontent.com/10796736/208844109-bb4fdd43-af13-45c0-9109-fc2d225d61fa.png)  | ![](https://user-images.githubusercontent.com/10796736/208844122-5da9a940-09a3-499b-9b7d-a54356bf1f08. …
=> Size information for Runtime Updates

src/Core/FlatpakBackend.vala, src/Core/Package.vala
Closes https://github.com/elementary/appcenter/issues/1310
=> Pretty output Flatpak package origins

src/Views/Homepage.vala
Fix appcenter crash if you activate a category while check for updates is in progress when the check completes.
=> Fix crash activating category while checking for updates

src/Core/Package.vala, src/Views/AppInfoView.vala
Closes https://github.com/elementary/appcenter/issues/1976
=> Fix warnings for native packages, OS and Runtime updates

src/Views/AppInfoView.vala, src/Views/AppListUpdateView.vala
Rewrites things to use a ListStore of packages which makes things like removing, sorting, adding, etc more straightforward. Separating handling data from handling UI
* Remove unused public methods
* Remove single-use methods
* Use functions from ListStore for clear and remove
* We don't need to check `os_updates` or `runtime_updates` before adding because we already do that
* Only call `show_all ()` when the model changes.
* We already refresh the model on `client.installed_apps_changed`, so we don't need to also explicitly call remove from the AppinfoView
=> AppListUpdateView: Rewrite with ListStore

src/Dialogs/StripeDialog.vala
I've noticed that the printf arguments in this string keep being re-ordered in some languages without adding positional specifiers which causes crashes. So let's add a translator comment to hopefully make it clearer.
=> StripeDialog: Add translator comment

src/Core/FlatpakBackend.vala, src/Core/PackageKitBackend.vala, src/meson.build
Since AppStream 0.16 AppCenter could no longer be compiled:
```sh
../../../downloads/elementary/appcenter/master/https_github.com_elementary_appcenter/src/Core/FlatpakBackend.vala:1044.74-1044.105: error: The name `COLLECTION' does not exist in the context of `AppStream.FormatStyle' (appstream)
1044 |         user_appstream_pool.add_extra_data_location (user_metadata_path, AppStream.FormatStyle.COLLECTION);
|                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../downloads/elementary/appcenter/master/https_github.com_elementary_appcenter/src/Core/FlatpakBackend.vala:1079.78-1079.109: error: The name `COLLECTION' does not exist in the context of `AppStream.FormatStyle' (appstream)
1079 | …
```
=> Fix deprecations for AppStream 0.16

src/Core/FlatpakBackend.vala
Fixes a bug where AppCenter crashes if only an user or a system installation of Flatpak remotes is available.
=> FlatpakBackend: Add null checks for user and system installation

src/MainWindow.vala, src/Views/SearchView.vala
Fixes #2059 
Fixes #1987 
It changes placeholder description to "The search term must be at least 3 characters long" when searching for something and then replacing that text with something else that is < 3 characters long.
=> Fix deletion of search term when replacing text with text

src/Widgets/AppContainers/AbstractAppContainer.vala
Changes from #1896 
* Inline namespace. Review with hide whitespace changes
* Subclass `Box` since there's no `Bin` in Gtk4
* Use `child` instead of `add` where appropriate
=> AbstractAppContainer: Gtk4 prep

src/Views/CategoryView.vala
Changes from #1896 
* Can't subclass Stack in Gtk4, so subclass Box
* Use `child` instead of `add`
* Fix spinner center align
=> CategoryView: Gtk4 prep

data/io.elementary.appcenter.gschema.xml
Require folks to opt-out of auto updates in onboarding instead of having to opt-in
=> gschema: default auto updates to true

.github/workflows/main.yml, src/Core/FlatpakBackend.vala, src/Core/Package.vala, src/Core/PackageKitBackend.vala, src/Views/AppInfoView.vala, src/Widgets/ReleaseRow.vala, src/meson.build
<details><summary>appstream-1.0.vapi</summary>
```csharp
/* appstream.vapi generated by vapigen, do not modify. */
[CCode (cprefix = "As", gir_namespace = "AppStream", gir_version = "1.0", lower_case_cprefix = "as_")]
namespace AppStream {
[CCode (cheader_filename = "appstream.h", type_id = "as_agreement_get_type ()")]
public class Agreement : GLib.Object {
[CCode (has_construct_function = false)]
[Version (since = "0.12.1")]
public Agreement ();
public void add_section (AppStream.AgreementSection agreement_section);
[Version (since = "0.12.1")]
public AppStream.AgreementKind get_kind ();
[Version (since = "0.12.1")]
public unowned AppStream.AgreementSection? get_section_default ();
[Version (since = "0.12.1")]
public unowned GLib.GenericArray<AppStream.AgreementSection> get_sections (); …
```
=> Add support for AppStream 1.0

src/Core/UpdateManager.vala
Don't check whether automatic updates are enabled when getting the update number. This has lead to an entry for runtime updates showing up with 0 updates available but having a download button. That's because there we check the download size not whether updates are available. 
The alternative to this PR would be to always exclude flatpaks when automatic updates are enabled however I think it's better to show the respective apps no matter whether automatic updates are enabled or not so that a manual update can always be forced and one can check progress on the automatic updates
=> UpdateManager: Get complete update number

src/Core/Client.vala, src/Core/Package.vala, src/Core/PackageKitBackend.vala, src/Core/UpdateManager.vala, src/MainWindow.vala, src/Views/AppInfoView.vala, src/Views/AppListUpdateView.vala, src/Widgets/AppContainers/AbstractAppContainer.vala, src/Widgets/AppContainers/AbstractPackageRowGrid.vala, src/Widgets/SizeLabel.vala
This doesn't completely remove packagekit because we use it for UbuntuDrivers
=> Remove OS updates

src/MainWindow.vala, src/Views/AppInfoView.vala, src/Views/CategoryView.vala
Replaces deprecated Adw.Leaflet with Adw.NavigationView
* Handles mouse buttons already
* Knows not to remove pages with `add` when they're popped
* Can't remove/pop arbitrary children, can only navigate back to that page
* Automatically removes popped children
=> MainWindow: Adw.Leaflet → Adw.NavigationView

data/io.elementary.appcenter.desktop.in.in
Update to look more like what appstream generator gives us with spaces between sections:
* Add desktop entry version
* Add SingleMainWindow to hint to the shell this app is not multi-window
=> Desktop: organize, add singlemainwindow

meson.build, src/Views/AppInfoView.vala
- Get license name from AppStream if >= 1.0 (if not SPDX license identifiers are used as before)
- Get license URL from AppStream instead of manually constructing
=> AppInfoView: Use AppStream API to get license info

debian/control
=> control: Require appstream >= 1.0.0

src/Widgets/Banner.vala
Solves a bunch of terminal warnings about `gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed`
=> Banner: get scale factor from window

data/appcenter.metainfo.xml.in, src/MainWindow.vala, src/Views/SearchView.vala
Fixes #554
* Makes it so you can start a search from any page
* Makes more searching logic internal to the search page
* You can have multiple searches without messing up your navigation history
* Will make it easy for each page to handle its own headerbar in a future branch
=> SearchView: make search_entry internal

src/Views/AppListUpdateView.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala
Makes it so more packages fit on screen at smaller window sizes:
* Wrap app names
* Make version labels small
* Use a reveal method that doesn't preserve space when hidden
* Make sure release notes revealers don't get margins when hidden
=> InstalledPackageRowGrid: make more compact

data/styles/HomePage.scss, data/styles/MainWindow.scss, src/MainWindow.vala, src/Views/AppInfoView.vala, src/Views/AppListUpdateView.vala, src/Views/CategoryView.vala, src/Views/Homepage.vala, src/Views/SearchView.vala, src/Widgets/BackButton.vala, src/meson.build
There's still a lot we can do to make better use of space in views like AppInfoView, but this gives us a canvas to pursue those things at least
Todo:
=> Views: supply own headerbars

src/Core/UpdateManager.vala
Fixes runtime updates not showing in updates list
This size check was added [here](https://github.com/elementary/appcenter/pull/1960), But we no longer create a "No runtime updates" package so we don't need this. A package is only inserted into the list if we find updates already
=> UpdateManager: remove runtime size check

src/Core/FlatpakBackend.vala, src/MainWindow.vala
* FlatpakBackend sets actions enabled while working, no need to have MainWindow do this, especially since we might not always have a window
* MainWindow: Set overlaybar properties in construct block not in constructor
* MainWindow: in close request get backend directly instead of property that's synced to this
=> MainWindow: remove working property

src/Core/FlatpakBackend.vala, src/Core/Job.vala, src/Core/Package.vala, src/Views/Homepage.vala
The installed check is queued and doesn't run until some more time intensive operations finish. However it is actually quite fast so IMO we can do it sync (I didn't notice any bad performance with this). Alternatively we can do it async but I think this might be worth doing on its own thread instead of queuing it as a job.
=> Fast start

src/Core/FlatpakBackend.vala
Accidentally introduced a crash in #2181
=> FlatpakBackend: set action enabled in main thread

src/MainWindow.vala
Fixes more memory leaks caused by https://gitlab.gnome.org/GNOME/vala/-/issues/1548
(the MainWindow wasn't freed when destroyed).
Also since we now always hold the application we don't have to hide the window to cancel updates since the flatpakbackend is static anyways. This also fixes #2166 and therefore closes #2168
=> MainWindow: Fix memory leaks + improvements

data/appcenter.metainfo.xml.in, data/icons/categories.gresource.xml, data/icons/link-vcs.svg, data/styles/AppInfoView.scss, po/POTFILES, src/Dialogs/StripeDialog.vala, src/Views/AppInfoView.vala, src/Widgets/HumbleButton.vala, src/Widgets/LinkListBox.vala, src/meson.build
Fixes #1134
Show more links, add some color. Group links related to contributing/giving vs requesting/contacting/receiving
=> AppInfoView: redesign links

src/Views/AppListUpdateView.vala
Because OS updates has been removed from AppCenter
=> AppListUpdateView: Avoid mentioning OS updates in user-facing texts

src/Core/UpdateManager.vala
* Fixes a regression where the update list would not be populated at all
* Moves auto updating all to `get_updates` and make it mutually exclusive with notifying
* Remove packages from the liststore as updates are installed instead of getting the list of updates twice
=> UpdateManager: Fix auto updates, liststore

src/Core/UpdateManager.vala, src/Views/AppListUpdateView.vala
UpdateManager:
* Make `update_all` its own function that is cancellable
* Make sure to use class-wide cancellable for auto updates
AppListUpdateView:
* Use update_all function from update_manager
* Make sure to set action buttons back to sensitive if update_all is canceled or errors
=> AppListUpdateView: DRY Update All

src/Application.vala
Destroying causes our cleaup in `close_request` to not run
=> Application: Close the window on quit, don't destroy it

src/Views/AppListUpdateView.vala
Fixes #2096 
I guess not having a stack widget visible before adding it to the stack can cause some inconsistent behavior with changing the visible child on the stack
**This is for OS7 Horus**
=> Fix inconsistent update view behavior

src/Core/FlatpakBackend.vala, src/Core/Package.vala, src/Views/AuthorView.vala
This is a first approach to support the new developer id (closes #2102). Although I added a new property to `Package.vala` populating that id, it is really uncommon that this info is available.
The "More apps from this developer" feature is kind of broken right now because of this... Should I search by author name like before in case no more apps are found?
I left some `warning` logs just to check the realted properties to this functionality in `FlatpakBackend.vala`.
=> Add support for new developer id

src/Views/AppInfoView.vala
Aims to implement #2210 
Will read the environment property of the screenshot and will filter it out if:
* _Prefer dark mode_ is true, and the screenshot _does not_ have a dark mode environment id (i.e. 'dark' in the environment ID). 
* _Prefer dark mode_ is false, and the screenshot _does_ have a dark mode environment id.
This won't consider null environments in the screenshots.
I have only tested this on the [Harvey](https://appcenter.elementary.io/com.github.danrabbit.harvey/) application, since this is the only app that I know has this implemented. I also tried a random assortment of titles with and without screenshots without any problems/crashes, though.
=> Filter screenshot by environment (elementary#2210)

src/Widgets/ReleaseRow.vala
Aims to fix #2224
The main issue was that the Issue box `LinkedButton` Label widget broke the natural sizing within the box when `wrap` was set to true. I'm not sure why this is the case, though. 
I could have removed the wrapping, but it would let issues too long and the boxes looked too odd. However, I managed to fix this by changing the `issue_boxes` GTK Widget to a Grid. This does detect and respect the natural size height changes when enabling wrap within a `LinkedButton` Label. 
This PR also contains three small additions:
* Changed the alignment of the cute bug icon so it centers better with the corresponding `LinkedButton` label (set `valign` to `Gtk.Align.BASELINE_CENTER`).
* Added a `margin_top` value on the "Fixed Issues" header to separate better the issues section from the …
=>  Made issue_box widget a grid (elementary#2224)

src/Core/Package.vala
Aims to fix #2140 
This will parse all the branding possibilities of the metadata info according to the freedesktop docs [here](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-branding).
The branding tag has a must-have color tag with `primary_color` attribute (always set its value to `primary`), with an optional `scheme_preference` attribute which shows a preference for a particular color scheme (withe light or dark) and this should take precedence.
But, as the issue says, there can be multiple setups here, and this PR aims to account for all of these in the following order:
* If the color tag has a `scheme_preference`, either set to light or dark, it should be taken as precedent, according to the desktop current color scheme (via …
=> Parse all branding colors from appstream (elementary#2140)

src/Application.vala, src/Core/UpdateManager.vala, src/MainWindow.vala, src/Views/AppListUpdateView.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala
This PR make several fixes around the `AppListUpdateView`, and the general Update packages behavior, namely:
1. Fixes #2215 _AppCenter still reserves space for system updates_
* The problem was related to the `vexpand` property of the `list_box`. When set to `true`
it would try to take as much space as possible. It's now set to `false` once the installed panel is visible with any available installed packages.
2. Fixes various issues around not showing properly the updates label.
* Those are the _"Everything is up-to-date."_ and _"Updates available"_ labels on the top. They should now show/hide properly according to the update behavior.
4. Disable the "Check for updates" menu button (set sensitive to `false`) when clicking on it, and enable it when the Flatpak backend stops again. This is …
=> Various fixes in AppListUpdateView

debian/appcenter.links
This PR prevents creating the dead symlink to `/usr/share/applications/io.elementary.appcenter-daemon.desktop` at `/etc/xdg/autostart/io.elementary.appcenter-daemon.desktop` which causes the following warnings on journal:
```
user@elementary:~$ journalctl -b | grep io.elementary.appcenter-daemon
Jan 02 03:32:02 elementary systemd-xdg-autostart-generator[1048]: /etc/xdg/autostart/io.elementary.appcenter-daemon.desktop: stat() failed, ignoring: No such file or directory
Jan 02 03:32:19 elementary systemd-xdg-autostart-generator[1372]: /etc/xdg/autostart/io.elementary.appcenter-daemon.desktop: stat() failed, ignoring: No such file or directory
Jan 02 03:32:19 elementary gnome-session[1666]: gnome-session-binary[1666]: WARNING: Desktop file …
```
=> Do not try to autostart the removed appcenter-daemon

src/Application.vala, src/Core/FlatpakBackend.vala
Fixes #2230
Based on the original code added in #403, plus avoid nested `if` and follow changes in the recent AppStream API.
=> Fix broken --load-local option

src/Core/FlatpakBackend.vala
This aims to fix #2246 
Forcefully deleting the cache will create an odd situation where the app loads the main banner and disappears after a few seconds (probably when the caches have been loaded in the worker thread), leaving the main window in an odd incomplete state.
This change looks up in the `FlatpakBackend.vala` constructor for the user and system cache metadata folders and will recreate them (via `preprocess_metadata`) if they are not found.
This will incur in a load time penalty. I believe this is not much of a big deal since this only happen if you explicitly delete the cache folders, which should be a rare occurrence in general.
Same procedure as set in the bug:
* Kill App Center
* Remove in `~/.cache` the folders `io.elementary.appcenter`, `flatpak` and `appstream` (you can …
=> Preprocess metadata cache if non-existing (issue #2246)

src/Views/AppInfoView.vala
This aims for a second round to complete the work to complete #2210 
This uses `XDG_SESSION_DESKTOP` and use either LIGHT or DARK `ColorSchemeKind` according to `gtk_application_prefer_dark_theme`.
Then it gets the screenshot environment metadata (described here: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots) to filter screenshots that match according to priority of environment first, color scheme second.
This triggers every time you open the AppView, so you should be able to exit the Appview, then change the color scheme then go back and see changes.
The environment IDs that currently exist in AppStream can be found here: https://github.com/ximion/appstream/blob/main/data/desktop-style-ids.txt
Notice that dark style specific the `:dark` suffix, …
=> Filter screenshots by style and environment (round 2)

data/styles/AppInfoView.scss, data/styles/Index.scss, data/styles/ReleaseRow.scss, src/Views/AppInfoView.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala, src/Widgets/ReleaseRow.vala
Fixes #2233 
Closes #2234
* Switch to boxes instead of adding an extra grid
* Do spacing and margins in CSS so they scale with text size
* Add card style class to make release notes easier to see borders of with light accent colors
=> ReleaseRow: fix overflow, improve styles

src/Widgets/AppContainers/InstalledPackageRowGrid.vala
This aims to fix #2033 
Added a `Gtk.ScrolledWindow` inside the release notes window. This has a fixed size that will show a scrollbar if the notes go beyond the expected size and avoid extra large release notes windows.
I managed to reproduce this on the [Colorful](https://flathub.org/apps/pl.suve.colorful) app
I tested other apps with different release notes layouts, and they worked ok, although none of them had the extremely long window height that Colorful had.
The `Gtk.ScrolledWindow` has a bit hardcoded part on `width_request` and `height_request` set `400x320`. Not sure if this could be a good solution, given my not broad knowledge on GTK4. If anyone has a better idea here, please, let me know to amend this PR.
=> Added a Gtk.ScrollingWindow to the Release notes dialog (issue #2033)

data/styles/Banner.scss, src/Views/AppInfoView.vala, src/Widgets/Banner.vala
Fixes deprecated adding provider to style context
If a brand color is available, creates a style provider with a css class for that color and adds it to a list of providers. Doesn't add a provider if no brand color available. Re-uses providers if two apps use the same brand color
=> Banner: create providers for display

data/styles/Index.scss, data/styles/SearchListItem.scss, data/styles/SearchPage.scss, src/Views/SearchView.vala
clamp results width, otherwise things get pretty silly with, for example a maximized window on a 30" monitor
=> SearchView: clamp results

src/Core/FlatpakBackend.vala, src/Widgets/AppIcon.vala
Does the least from #2238 to fix #2209
Doesn't include any of the fancier stuff like making fallback images look nice or fading between them
=> AppIcon: reload on metadata remote preprocessed

debian/control
We then do not need the AppStream data either
Closes: https://github.com/elementary/default-settings/issues/255
=> Remove packagekit from the dependency chain

src/Views/AppInfoView.vala
Initial support for listing things an app supports, starting with controllers. Eventually this will also include things like mobile support, etc. I made this a separate list from content warnings because I think it's less important and doesn't need to be "above the fold" like content warnings do
=> AppInfoView: show when a game supports controllers

src/Views/AppInfoView.vala
Uses considerably less vertical space since most apps don't have a ton of warnings
=> AppInfoView: layout content warnings horizontally

src/Core/FlatpakBackend.vala
marking installed results in an update state call which in turn results in
1. a notify signal for state to which a bunch of ui components are connected which leads to incosistencies and crashes with gtk not being threadsafe
2. since the list models pr an items_changed in the list models to which a bunch of other stuff is connected with the same problems as 1
I think in general we should be much more careful with doing things like that in the worker thread (e.g. #2306 comes to mind) since I could imagine a good portion of crashes currently are due to us calling methods or emitting signals from the worker thread or not being aware they are emitted from the worker thread.
Fixes a crash that sometimes occurs when trying to start appcenter silently and probably a bunch of incosistencies when …
=> get_installed_applications: mark installed on main thread

src/Application.vala, src/Core/FlatpakBackend.vala, src/Core/UpdateManager.vala, src/Dialogs/UpdateFailDialog.vala, src/MainWindow.vala, src/Views/AppListUpdateView.vala
This PR streamlines the refresh flow. We now do everything in the update manager which will automatically start the timeout if we're less than 24 hours from the last update or else refresh immediately.
We also now only refresh after the network comes available if we tried to refresh while the network wasn't available.
This doesn't include but prepares for more behavioral changes proposed in #2214 
Also prepares for some cleanup of the refresh action enabled logic which is left to another PR
`cancel_updates` was removed because it was only used to cancel updates
1. when disabling automatic updates which isn't necessary anymore since the user now sees that the apps are updating and can cancel the update manually if they wish to
2. when the app window was closed which I don't get anyways why …
=> Streamline refresh flow

data/styles/HomePage.scss, src/Widgets/AppIcon.vala
We should be consistent here. If there needs to be design changes to the default icon we should do that in the icon set and not as a (expensive) CSS filter.
See also: https://github.com/elementary/icons/pull/1380
=> Styles: remove placeholder app icon dim

po/POTFILES, src/Dialogs/ReleasesDialog.vala, src/Widgets/AppContainers/InstalledPackageRowGrid.vala, src/meson.build
Use a list of cards for releases in the release dialog and make it its own class. I eventually want to use it in AppInfoView as well
=> Create ReleasesDialog.vala and redesign

src/Core/ODRSProvider.vala
Check that n_ratings > 0 after the iterator so we don't accidentally divide by 0
=> ODRSProvider: avoid floating point exception

src/Core/ODRSProvider.vala, src/Views/AppInfoView.vala
- out variables does not need to be initialized explicitly in the calling side
- Use return value instead of out parameters to check if the method succeeds
- Make sure to set values to the out parameters only when the method succeeds
=> ODRSProvider: Result as return value, set out parameters only when succeeds
